scikit-hep/boost-histogram

notebooks/PerformanceComparison.ipynb
src/histogram/histogram.cpp

Generic fill for scalars and arrays. Tests are missing, because I cannot run tests from my build directory. Need to investigate.
You can do any of the following:
```
h1d(1)
h1d([1, 2, 3])
h2d(1, 2)
h2d([1, 2], [3, 4])
h4d([1], [2], [3], [4])
```

implemented generic ND fill

---

CMakeLists.txt
include/boost/histogram/python/axis.hpp
src/histogram/axis.cpp
tests/test_histogram_internal.py

This currently cases the following error:
<details><summary>
Click to expand
</summary>
```
In file included from /Users/henryiii/git/software/histogram-python/src/histogram/histogram.cpp:10:
In file included from /Users/henryiii/git/software/histogram-python/include/boost/histogram/python/axis.hpp:7:
In file included from /Users/henryiii/git/software/histogram-python/extern/histogram/include/boost/histogram.hpp:25:
In file included from /Users/henryiii/git/software/histogram-python/extern/histogram/include/boost/histogram/algorithm/project.hpp:12:
In file included from /Users/henryiii/git/software/histogram-python/extern/histogram/include/boost/histogram/histogram.hpp:10:
In file included from /Users/henryiii/git/software/histogram-python/extern/histogram/include/boost/histogram/detail/ax …
```

Adding axis::ariable

---

src/histogram/axis.cpp
src/histogram/histogram.cpp
tests/test_axis_internal.py
tests/test_make_histogram.py

This fixes a lifetime bug (something named `lightweight_view` should have made it pretty obvious that a `keep_alive` was needed!), as well as enables string bins (categories) to be accessed. Still no fill for non-double axis. It would also be nice if there was a trait that could detect a real axis from a category one.

Adding a slighly more comprehensive test

---

include/boost/histogram/python/axis.hpp
src/histogram/axis.cpp
tests/test_axis_internal.py

This could be used to attach units, for example.

Allow any python object for a label

---

setup.py
src/histogram/accumulators.cpp
src/histogram/axis.cpp
src/histogram/histogram.cpp
src/module.cpp
tests/test_accumulators.py
tests/test_axis_internal.py
tests/test_make_histogram.py

This adds support for the built-in accumulators, mostly in case a histogram returns one, but also has vectorized (numpy sense) accumulation.
Renamed parameter x to value in a few cases, and providing `__call__` interface even when B::H does not (not sure how I feel about that; even VI is complaining about ignoring the return value of a "function".)
Also renames label -> metadata. Followup to #15, discussed in #14.

Accumulators

---

.gitignore
CMakeLists.txt
README.md
notebooks/AtomicHistograms.ipynb
notebooks/DevelopInstallExample.ipynb
notebooks/PerformanceComparison.ipynb
setup.py
tests/test_accumulators.py
tests/test_atomic_fill.py
tests/test_axis_internal.py
tests/test_basic_import.py
tests/test_histogram_internal.py
tests/test_make_histogram.py

Move to subdirectory, now called boost.histogram. Note that __init__.py must match all other packages with the "boost" name.

Rename histogram -> boost.histogram

---

CMakeLists.txt
include/boost/histogram/python/axis.hpp
src/histogram/axis.cpp
src/histogram/histogram.cpp
tests/speed_numpy.py
tests/test_atomic_fill.py
tests/test_axis_internal.py
tests/test_histogram_internal.py
tests/test_make_histogram.py
tests/test_public_axis.py
tests/test_public_hist.py

This:
* fixes a few warnings
* Allows "make_regular" function shortcut (name may change to "regular" at some point)
* Renames regular and integer to `*_uoflow` versions.
* CMake defaults to "release" mode

Drop some warnings, regular_base

---

include/boost/histogram/python/histogram.hpp
include/boost/histogram/python/pickle.hpp
setup.py
src/histogram/accumulators.cpp
src/histogram/axis.cpp
src/histogram/histogram.cpp
src/histogram/make_histogram.cpp
src/histogram/storage.cpp
src/module.cpp
tests/test_accumulators.py
tests/test_pickle.py
tests/test_public_hist.py

This uses built-in pickle support, combined with Python types, to do serialization.  Standard PyBind11 caveats for picking in Python 2 apply (must be cPickle, must use a reasonably high pickle protocol).
Also provides high quality copy machinery. TODO: add proper deep copy support for histograms (plain axis already fixed).

Henryiii pickle

---

.ci/azure-cmake-steps.yml
.ci/azure-macos-setup.yml
.ci/azure-publish-dist.yml
.ci/azure-setup.yml
.ci/azure-steps.yml
.ci/azure-submodules.yml
.ci/azure-upload.yml
.ci/build-wheels.sh
.ci/macos-install-python.sh
.gitignore
MANIFEST.in
README.md
azure-pipelines.yml
dev-requirements.txt
setup.py
tests/test_axis_internal.py

SDists can now be created, and wheels are built. They are reasonably clean (but please don't have too much extra stuff in your directory when making them). Parallel building now supported if Numpy is installed. Fixed a test that could fail in rare cases, especially on 32-bit builds.
| System | Arch | Python versions |
|---------|-----|------------------|
| ManyLinux1 (custom GCC 8.3) | 64 & 32-bit | 2.7, 3.5, 3.6, 3.7 |
| ManyLinux2010 | 64-bit | 2.7, 3.5, 3.6, 3.7 |
| macOS 10.9+ | 64-bit | 2.7, 3.6, 3.7 |
| Windows | 64 & 32-bit | 3.6, 3.7 |
* Linux: I'm not supporting 3.4 because I have to build the Numpy wheels to do so.
* manylinux1: Using a custom docker container with GCC 8.3; should work but can't be called directly other compiled extensions unless they do the same thing (think …

SDist and Wheels

---

src/histogram/histogram.cpp
tests/test_histogram_internal.py
tests/test_public_axis.py
tests/test_public_hist.py

This makes `np.asarray(hist).sum() == hist.sum()`.

Change asarray to ignore flow bins, fix warnings from tests

---

include/boost/histogram/python/kwargs.hpp
scripts/performance_report.py
src/histogram/histogram.cpp
tests/test_atomic_fill.py
tests/test_benchmark_1d.py
tests/test_benchmark_2d.py
tests/test_histogram_internal.py
tests/test_public_hist.py

This is more clever in handing kwargs, so that fill(, **kwarg) can be supported. Signatures will still need to be carefully done by hand.
This renames `__call__` to fill. A simpler `__call__` could be added eventually which mimics C++, but probably not at the cost of compile time.

Rename `__call__` to fill, add kwarg handlers

---

.clang-format
azure-pipelines.yml
examples/guide_mixed_cpp_python.cpp
include/boost/histogram/python/axis.hpp
include/boost/histogram/python/copyable_atomic.hpp
include/boost/histogram/python/histogram.hpp
include/boost/histogram/python/histogram_atomic.hpp
include/boost/histogram/python/histogram_fill.hpp
include/boost/histogram/python/histogram_threaded.hpp
include/boost/histogram/python/kwargs.hpp
include/boost/histogram/python/pickle.hpp
include/boost/histogram/python/pybind11.hpp
include/boost/histogram/python/storage.hpp
include/boost/histogram/python/try_cast.hpp
scripts/check_style.sh
scripts/check_style_docker.sh
src/histogram/accumulators.cpp
src/histogram/axis.cpp
src/histogram/histogram.cpp
src/histogram/make_histogram.cpp
src/histogram/storage.cpp
src/histogram/version.cpp

Add clang-format, and apply formatting. ~~This is not being checked yet by CI to keep PRs fast and simple.~~ Okay, yes, they are checked.
On a system with docker, run `scripts/check_style_docker.sh`, or run `scripts/check_style.sh` if you have a recent Clang-Format (5.0 is too old).

Clang format

---

CMakeLists.txt
include/boost/histogram/python/axis.hpp
include/boost/histogram/python/pybind11.hpp
include/boost/histogram/python/register_accumulator.hpp
include/boost/histogram/python/register_axis.hpp
include/boost/histogram/python/register_histogram.hpp
include/boost/histogram/python/register_storage.hpp
src/histogram/accumulators.cpp
src/histogram/axis.cpp
src/histogram/histogram.cpp
src/histogram/make_histogram.cpp
src/histogram/storage.cpp
src/module.cpp
tests/test_axis_internal.py
tests/test_public_axis.py

* Moving code to headers, so this can be extended more easily by users
* Cleanup for names and registration functions to make them nicer to use
* Automatically add IV to axis if they support it
* PyTest now works a bit better with the CMake build
* `metadata_t` cannot be numeric if in the constructor of an axis. (Common mistake)
* overflow and underflow separate, and supported for integer and variable axes (increased variant size)
* Shortcut `flow=` still works and overrides other selections.

Axes types

---

README.md
include/boost/histogram/python/kwargs.hpp
src/histogram/make_histogram.cpp
tests/test_make_histogram.py
tests/test_public_hist.py

This makes the following equivalent:
```python
bh.histogram((10, 0, 1, "x"), [0, .5, .6, .9, 1.2])
```
```python
bh.histogram(bh.axis.regular(10, 0, 1, "x"), bh.axis.variable([0, .5, .6, .9, 1.2]))
```
A final string can be detected and used as metadata.

Adding shortcut for regular and variable axes

---

src/histogram/make_histogram.cpp
tests/test_make_histogram.py
tests/test_public_hist.py

This removes the potentially controversial change from #47. This can be discussed later in a proper PR or issue.

Dropping list shortcut for variable axes

---

include/boost/histogram/python/pickle.hpp
include/boost/histogram/python/register_accumulator.hpp
include/boost/histogram/python/register_axis.hpp
include/boost/histogram/python/register_histogram.hpp
include/boost/histogram/python/register_storage.hpp
include/boost/histogram/python/serializion.hpp
tests/test_public_hist.py

Restructured serialization to more closely resemble official serialization headers. It would be nice if some of the code could be shared to reduce changes in the future.

Moving to latest Boost::Histogram develop, adding shrink and rebin

---

CMakeLists.txt

As requested by @HDembinski, a CMake user will now get an error sooner if they don't have pytest-benchmark.
TODO: Fix the name so that it says `pip install pytest-benchmark` instead of `pip install pytest_benchmark`. Have I mentioned that dashes in package names are irritating? ✅ 
Closes #63.

CMake checks for dev packages when configuring

---

.gitmodules
include/boost/histogram/python/serializion.hpp

This version has the private variant implementation, which together with a few other things now allows us to drop most of the external dependencies.

Update to new histogram version

---

.ci/azure-live-at-head-pipeline.yml
.ci/azure-live-at-head.yml

Adding a weekly check for the most recent develop or master branches of all dependencies. Based on Google's live at head philosophy.

Adding live at head check

---

README.md
docs/_src/images/axis_category.tex
include/boost/histogram/python/axis.hpp
notebooks/PerformanceComparison.ipynb
scripts/performance_report.py
src/histogram/axis.cpp
src/histogram/general_histograms.cpp
src/histogram/make_histogram.cpp
tests/speed_numpy.py
tests/test_axis_internal.py
tests/test_histogram_internal.py
tests/test_make_axis.py
tests/test_make_histogram.py
tests/test_pickle.py
tests/test_public_axis.py
tests/test_public_hist.py

This PR renames the rest of the axes and the histograms to private names; the only publicly supported way to create a histogram or axis is through the creation tools like `histogram()` and `regular()`.

Private rename

---

.ci/azure-test-pipeline.yml
README.md
docs/index.rst
docs/indexing.rst
include/boost/histogram/python/register_histogram.hpp
include/boost/histogram/python/serializion.hpp
include/boost/histogram/python/shared_histogram.hpp
include/boost/histogram/python/typetools.hpp
include/boost/histogram/python/variant.hpp
setup.py
src/histogram/algorithm.cpp
src/histogram/shared_histogram.cpp
src/histogram/utils.cpp
src/module.cpp
tests/test_accumulators.py
tests/test_axis_internal.py
tests/test_basic_import.py
tests/test_benchmark_1d.py
tests/test_benchmark_2d.py
tests/test_histogram_internal.py
tests/test_indexed.py
tests/test_indexing.py
tests/test_make_axis.py
tests/test_make_histogram.py
tests/test_pickle.py
tests/test_public_axis.py
tests/test_public_hist.py
tests/test_threaded_fill.py

This reworks the reduce support to match Boost::Histogram (I realized the old version was inspired by the original Python bindings). Most users should use #35, which is included now (at least in part). The Boost::Histogram based methods do less Python magic, so will be faster if a user indexes a *lot* (thousands to millions of times in a loop). I have left off the "shortcut" 1D methods because of this, but I could add them for constancy.
* Setting is not supported (deferred for a later PR)
* Slice/shrink + projection is not supported (deferred for a later PR)
Other features of this PR:
* Black formatting for Python now tested
* Docs updates.

Fancy indexing, reduce from Boost.Histogram

---

include/boost/histogram/python/indexed.hpp
include/boost/histogram/python/register_histogram.hpp
src/histogram/algorithm.cpp
src/histogram/general_histograms.cpp
src/histogram/make_histogram.cpp
src/histogram/utils.cpp
tests/test_profiles.py
tests/test_public_hist.py

This enables profile histograms and sampled fills.
It also drops the required `()` after a storage (`storage=bh.storage.profile` is now valid, for example, instead of only `storage=bh.storage.profile()`).

Sampled fills and profile histograms

---

src/histogram/make_histogram.cpp

histograms are not numpy arrays and a storage is not a numpy array. The dtype argument is teaching people the wrong ideas about this class.

Remove dtype argument

---

include/boost/histogram/python/axis_ostream.hpp
include/boost/histogram/python/histogram_ostream.hpp
include/boost/histogram/python/register_axis.hpp
include/boost/histogram/python/register_histogram.hpp
include/boost/histogram/python/storage.hpp
scripts/check_style.sh
tests/test_public_axis.py
tests/test_public_hist.py

Fixes part of #90; the repr's are now stable and provide Python-ready syntax. This does not add a quick way to preview the contents of histograms or the bin edges, might be in a later PR.

Python-ready repr

---

.ci/azure-setup.yml
.ci/azure-steps.yml
.ci/azure-test-pipeline.yml
.gitignore
.pre-commit-config.yaml
.pre-commit-nodocker.yaml
.readthedocs.yml
README.md
boost_histogram/axis.py
boost_histogram/axis/options.py
docs/_src/images/axis_circular.tex
docs/_src/images/axis_regular.tex
docs/_src/images/axis_variable.tex
docs/usage/comparison.rst
docs/usage/quickstart.rst
include/boost/histogram/python/axis.hpp
include/boost/histogram/python/register_axis.hpp
src/module.cpp
src/register_axis.cpp
tests/test_axis_internal.py
tests/test_axis_options.py
tests/test_pickle.py
tests/test_public_axis.py

Something like this is what I'm thinking. I'm not fond of namedtuple for this use case due to *some* of the reasons listed [here](http://www.attrs.org/en/stable/why.html#namedtuples), though the current design I've used is similar and could switch to using them. I can't think of anywhere in the standard library they are used like this; normally the Python standard library would use a [SimpleNamespace](https://docs.python.org/3/library/types.html#types.SimpleNamespace), but that's Python 3.3+ only.
NamedTuples are good for functions that return multiple values and maintaining backward compatibility, but they are inherently structured, so support unpacking, comparing, iteration, etc. They are also almost the only place in Python where `_X` names are not intended to be private (due to …

Starting axis options

---

setup.py

This follows up on #14 
* `with` used for reading file
* `exec` used with a dictionary - this makes it clear to humans and IDEs where `__version__` comes from - the short form of exec is like `from x import *`
* Paths are now all compared to setup.py's location rather than the current working dir.
- I used a simple shim to keep from adding pathlib2 as a dependency for Python2 but still keep the syntax reasonable, IMO.

Setup updates

---

boost_histogram/axis.py
boost_histogram/utils.py
include/boost/histogram/python/kwargs.hpp
src/register_axis.cpp
tests/test_axis.py
tests/test_pickle.py

All arguments are now keyword only, except the basic ones unique to an axis type. The creation functions are now written in Python. The axis init c++ function is now able to add init arguments like arguments names. All creation functions support keyword arguments now, including private ones.
Not that direct axis creation, like `regular_*`, still allow metadata to be passed by position for now. Help and signature are not ideal yet.

Move make functions to Python, keyword only

---

boost_histogram/__init__.py
boost_histogram/_hist.py
boost_histogram/utils.py
docs/usage/indexing.rst
include/boost/histogram/python/register_histogram.hpp
tests/test_public_hist.py

Closes #35.
Improvements to setitem indexing are shared with getitem.
Array/histogram setting is deferred for a later release.

Adding setitem, overflow/underflow

---

boost_histogram/_hist.py
include/boost/histogram/python/register_histogram.hpp

Adding this simplifies the Python portion of the bindings. @HDembinski, I've made this hidden, but I'm open for name suggestions. I'm not sure if `_storage_class` or `_storage_type` is better - they are somewhat interchangeable in Python.

Storage class

---

src/register_accumulators.cpp
tests/test_accumulators.py

Closes #129. Provides a `.fill` method and makes weight/variance keyword only.

Adding accumulator fill and kw arguments

---

boost_histogram/__init__.py
boost_histogram/_hist.py
boost_histogram/accumulators.py
boost_histogram/algorithm.py
boost_histogram/axis.py
boost_histogram/numpy.py
boost_histogram/storage.py
boost_histogram/utils.py
include/boost/histogram/python/axis.hpp
include/boost/histogram/python/axis_setup.hpp
include/boost/histogram/python/options.hpp
include/boost/histogram/python/register_axis.hpp
include/boost/histogram/python/register_histogram.hpp
include/boost/histogram/python/regular_numpy.hpp
src/register_axis.cpp
tests/test_numpy.py
tests/test_pickle.py

This adds numpy compatibilty functions, as well as corrected to_numpy, now designed to properly perform a round-trip conversion to a numpy edges array. Variable bins fully round trip.  ~~The other direction is not quite correct for regular bins, since `regular()` does not have numpy's special final edge handling - this is as close as possible for the moment.~~ Adds a custom `_regular_numpy` axis type, only used by this method, that has the special case edge handling. See [histogram.guide.expert.user_defined_axes](https://www.boost.org/doc/libs/1_71_0/libs/histogram/doc/html/histogram/guide.html#histogram.guide.expert.user_defined_axes).
Will check an item off on #91; the rest of that issue will be deferred till a later release.
Note there are rounding differences on bin edges. But this …

Numpy compat

---

boost_histogram/_hist.py
tests/test_indexing.py

This corrects the projection UHI implementation, and fixes the test so that it actually reports an error if it doesn't work (oops).
Fixes #139.

Fix projections and fix test for projection, add sum behavior

---

CHANGELOG.md
README.md
boost_histogram/__init__.py
boost_histogram/_hist.py
boost_histogram/numpy.py
include/boost/histogram/python/regular_numpy.hpp
tests/test_numpy.py

This uses keyword only arguments in the numpy functions, and removes the warning on import (the import is automatic again).
Also removes a debug print (oops).

Keyword numpy

---

setup.py

May help in cases where paths are being resolved to WSL paths for some reason. Closes #161 if it works.

Always use relpath in setup.py

---

boost_histogram/__init__.py
boost_histogram/_hist.py
boost_histogram/_utils.py
boost_histogram/axis.py
boost_histogram/numpy.py
boost_histogram/uhi.py
docs/usage/indexing.rst
tests/test_indexing.py

This also moves the files around just a bit - UHI components are now exported from `uhi.py` instead of `utils.py`, and `_utils.py` is now private. Closes #152

Adding offset to UHI

---

boost_histogram/_hist.py
include/boost/histogram/python/register_histogram.hpp
tests/test_histogram_internal.py
tests/test_make_histogram.py
tests/test_pickle.py
tests/test_public_hist.py

See #155. This should keep too many users from depending on these features slated for removal from the "pythonic" part of the bindings when the `cpp` module is added.

Deprecation for at and axis

---

include/boost/histogram/python/accumulators_ostream.hpp
include/boost/histogram/python/axis.hpp
include/boost/histogram/python/histogram.hpp
include/boost/histogram/python/register_histogram.hpp
src/register_histograms.cpp

This is the beginning of work for a `_copy_in` function; this will power (at least) `h[...] = np.array(...)`, and maybe operations with histograms and arrays. Going to get this working with doubles first, then generalize.
Currently, double only.

Adding copy_in

---

CHANGELOG.md
README.md
boost_histogram/__init__.py
boost_histogram/_internal/hist.py
boost_histogram/tag.py
docs/usage/indexing.rst
include/boost/histogram/python/register_histogram.hpp
tests/test_indexing.py
tests/test_public_hist.py

This brings UHI more inline with the original proposal from @jpivarski , and removes the internal tags originally required (`.value` and `.offset`). The original proposal is that the indexers would be callable functors, and they would receive the axis when being called. This simplifies `bh.loc`, and also makes it much easier for users to write there own. In fact, `len` naturally works:
```python
h[0:len:bh.project]
```
Will sum without including the flow bins. This also includes the trick proposed by @HDembinski, where cropping is simulated through setting flow bins on a copy to 0, so it now finally allows limits on sums! Closes #135. `bh.sum` is available now, as well, though `bh.project` is still around for the moment.
We need to think a little about the difference in slicing and direct …

UHI update

---

README.md
boost_histogram/_internal/axis.py
boost_histogram/_internal/hist.py
boost_histogram/_internal/sig_tools.py
tests/test_sigs.py

This allows Python 3 to get nice signatures while still supporting Python 2. Closes #144.
The histogram and axes constructors (and fill) all have nice signatures now to go along with the nice docstring. When we drop Python 2.7, the contents of the decorator strings can replace current signatures and the decorator (and most/all of the KWArgs tool) will go away.

Adding signature decorator

---

boost_histogram/__init__.py
boost_histogram/_internal/hist.py
boost_histogram/axis/__init__.py
tests/test_boost_histogram.py

This closes #206, and adds the `.at` and `.axis` back for one release, with more prominent warnings.

Ensure warnings show up

---

boost_histogram/_internal/hist.py
tests/test_public_hist.py

Closes #209.
Matching Pandas in design, except we make `deep` a keyword only argument, since we don't have to be backward compatible and because we may end up adding other functionality to `.copy`.

Adding .copy()

---

boost_histogram/_internal/axis.py
boost_histogram/_internal/hist.py
boost_histogram/axis/__init__.py
boost_histogram/cpp/axis/__init__.py
boost_histogram/numpy.py
include/boost/histogram/python/axis.hpp
include/boost/histogram/python/register_axis.hpp
src/register_axis.cpp
tests/test_axes_object.py
tests/test_axis.py
tests/test_cpp_interface.py
tests/test_histogram.py
tests/test_internal_histogram.py
tests/test_pickle.py

Fixes #215 by splitting Category into IntCategory and StrCategory. You can now make an empty category axis.
Some cleanup of the axis creation, and removing internal docstrings.
~~@HDembinski, would a possible workaround for now (in the bindings) be to create the default constructed axis, then set the metadata manually? Would there be any potential issues? It would be nice to be compatible with Boost 1.72's Histogram for the moment.~~ 
~~(Implemented)~~
@HDembinski already fixed this in Boost.Histogram, so now using that here!

Str/Int Categories

---

.gitignore
CMakeLists.txt
include/boost/histogram/python/register_histogram.hpp
tests/test_histogram.py

Fixes the issues in #214 reported by @nsmith-
```py
h = bh.Histogram(bh.axis.StrCategory([], growth=True), bh.axis.Integer(0, 1))
h.fill(["a"], [1, 2])
```

Fix fill issues

---

include/boost/histogram/python/register_histogram.hpp
tests/test_histogram.py

~Now the broadcasts work like in numpy~, passing arrays of different size is an error, but scalar and array works, the scalar is broadcast. This fixes the segfault of nsmith

Fix fill segfaults and broadcasting misbehavior

---

boost_histogram/_internal/axis.py
boost_histogram/_internal/axis_transform.py
boost_histogram/_internal/hist.py
include/transform.hpp
src/register_transforms.cpp
tests/test_pickle.py

The wrapped design was not copying anything on a shallow copy, as this now was skipping the `._this`/`._hist`/`._ax` attribute as "deep". (I may rename all of them to `_this` for consistency later).
Fix #220 again; this time after copies.
Pickling transforms was broken due to a missing line, fixed.
TODO:

Fix shallow copy, axis staleness, transform pickle

---

.ci/azure-test-pipeline.yml
.github/workflows/pre-commit.yml
README.md

Using GitHub Actions, does not checkout submodules, closes #69. Formatting can complete in 23 seconds instead of 1 minute.
Implemented using https://github.com/pre-commit/action/issues/1.
Sadly, there's still no way to say "Reformat, please" to get it to reformat. But that may happen at some point.

Move formatting to Github Actions

---

CMakeLists.txt

This adds a way for developers to monitor the compile stats. Ideally, you probably should build a single target, like `src/register_histograms.o` or build with a single core, `-j1` (the default with make).

Add way to check the approx compile info

---

boost_histogram/_internal/hist.py
tests/test_pickle.py

The tests added in #237 measure performance, so this adds benchmarks to handle the slow-pickle testing. Also simplifies the histogram pickle by not repickling the cached axes.
Run with:
```bash
python3 -m pytest --benchmark-enable --benchmark-sort fullname ../tests/test_pickle.py
```
Current result (I reduced the number from 10000 to 1000 for these runs accidentally, similar results x 10 if you use the current length):
```
---------------------------------------------------------------------------------------------------------- benchmark '1d-fills': 32 tests ----------------------------------------------------------------------------------------------------------
Name (time in us)                                                            Min                   Max                Mean …
```

Pickle touchup

---

boost_histogram/numpy.py
tests/test_numpy_interface.py

Numpy interface was missing density, now it's easy to calculate, so adding it back in. Also fixed a bug where the requested storage type was being ignored.

Add density to numpy

---

boost_histogram/_internal/hist.py
tests/test_cpp_interface.py
tests/test_histogram.py

The original idea was to add `.show()` to generate the text rendering, with possibly some options on how to render. Then `.__str__(self)` would call `.show()`. However, this does not work well in the REPL, unless `.show()` returns a special string class that has a modified `__repr__(self)`:
```
In [8]: h.show()
Out[8]: 'histogram(regular(10, 0, 1, metadata="None", options=underflow | overflow))\n              +--------------------------------------------------------------+\n[-inf,   0) 0 |                                                              |\n[   0, 0.1) 0 |                                                              |\n[ 0.1, 0.2) 0 |                                                              |\n[ 0.2, 0.3) 0 | …
```

Adds `__str__` which generates a text rendering

---

boost_histogram/_internal/hist.py
tests/test_histogram.py

This is a common part of the numpy syntax that also makes sense on Histograms.

Add .shape

---

boost_histogram/_internal/hist.py
tests/test_histogram.py

This fixes half of #263, the Histogram part. Follows the original Boost.Histogram design with single line repr for 1D, and prints properly for 0D (and added tests). May need to need to be merged with changes in #262.

Fix repr for 1 and 0d

---

boost_histogram/_internal/view.py
tests/test_storage.py

Very irritating bug due to late binding (which I thought I'd fixed/checked, but apparently not). All non-computed properties on views for accumulators return the same set of values. So `h.view().value` is not the value, but the final property, etc.

Fixing bug in view property access

---

boost_histogram/_internal/hist.py
tests/test_histogram.py

Division was not handled in the wrapper for scalars. Closes #275.

Updates for divide

---

CHANGELOG.md
boost_histogram/_internal/hist.py
docs/usage/indexing.rst
tests/test_histogram_indexing.py

This allows single values in indexing expressions, allowing:
```python
hist[a:b, c]
```
as a replacement for
```python
hist[a:b, c:c+1:bh.sum]
```
(Basically it works just like Numpy). It also fixes a bug related to setting with a length 1 slice. Also, the following now works as it should:
```python
h[:, 3] = a_1d_array
```
(Was buggy before)

Allow single value (fix several setting bugs)

---

boost_histogram/_internal/axis.py
tests/test_axis.py

Single item UHI should work on axes indexing.
(Working on examples and docs)
(Slices as a way to slice axes would be very useful too, but should be a 0.7 feature)

Add single-element UHI to axis

---

boost_histogram/numpy.py
tests/test_numpy_interface.py

The Numpy adaptor will fail if a Numpy int instead of a python int is used for bins. This fixes that check.

Fixing numpy failure for numpy int with bins

---

CHANGELOG.md
boost_histogram/_internal/hist.py
include/register_histogram.hpp
tests/test_histogram.py

Inplace add was simply falling back to out-of-place add; the binding for inplace add was missing.
Also improved the inplace operations to not change the python object ID either.

Fix missing inplace add, nicer inplace

---

CHANGELOG.md
boost_histogram/_internal/hist.py
tests/test_histogram_indexing.py

Fix issues with indexing and summing category axes. You can now sum over a category axes again (regression in 0.6.0), and you can select a single item from a category axes just like you can from other axes types.
Fixes #297, improves #296 (single item selection now works on a category axis).
This may be improved upstream in Boost.Histogram later, in which case this can be simplified eventually.

Fixing category indexing

---

boost_histogram/_internal/hist.py
tests/test_histogram_indexing.py

Fix typo that causes the *upper* bound of the range to not be respected if the underflow bin is off.
This does not affect 0.6.1 because summation over anything with flow turned off was broken.

Use slices again for single item selection

---

boost_histogram/_internal/axistuple.py
tests/test_axes_object.py

Just noticed that this was not available, but it should be.

Allow metadata to be set on AxesTuple

---

.ci/azure-live-at-head-pipeline.yml

Broken since the update to the latests azure-wheel-helpers. As a reminder, this runs every Sunday but is not very well exposed. Maybe it could become a badge or something similar.

Live at head pipeline fix

---

.ci/azure-build-pipeline.yml
.ci/azure-test-pipeline.yml
.ci/azure-wheel-helpers/README.md
.ci/azure-wheel-helpers/azure-pipeline-build.yml
.ci/azure-wheel-helpers/azure-steps.yml
.ci/azure-wheel-helpers/azure-tests.yml
.ci/azure-wheel-helpers/build-wheels.sh
CHANGELOG.md
setup.cfg
setup.py

This drops the deprecated `setup.py test` syntax, updates the changelog, and attempts to fix #169. ~~If the fix works, this will need 793c3dd pushed up to the subtree (I haven't done that before, so might have to work on that for a bit).~~ Pushed to Azure-wheel-helpers, and updated the README with instructions.
(Note: merging this does *not* mean 0.7.0 is released, there are at least two more issues to be addressed, the readme banner needs to be removed.)

Cleanup and preparation for 0.7.0

---

src/boost_histogram/_internal/hist.py

I was playing with the `bh.numpy` API and I noticed this print statement is always reached when `threads` is not `None`. I'm assuming printing an object any time a particular argument is present is not desired behavior

Remove unncessary print statement

---

src/boost_histogram/_internal/hist.py
tests/test_cpp_interface.py

Note: As part of this patch, I moved the `.view` from the main interface into the base interface, so that the cpp interface can also use it.
This adds a test for the cpp-style `sum` to check that the default behavior is as in C++.

Test cpp sum

---

setup.py
src/boost_histogram/__init__.py
tests/test_pickle.py

This is a bit hacky, a better fix should come from cloudpickle or pybind11. Fixes #342.
This is correctly fixed in https://github.com/cloudpipe/cloudpickle/pull/357 - when that is merged and released, this can simply become a test with a new version of cloudpickle.

Allow cloudpickle to work on histograms

---

src/boost_histogram/_internal/hist.py

TODO: Could add a test; static typing would have caught this too. Maybe consider normalizing all the hidden method return types?
Discovered in https://github.com/scikit-hep/hist/pull/22

fix: extra Python wrapper removed

---

setup.cfg
src/boost_histogram/_internal/axis.py
src/boost_histogram/_internal/hist.py
tests/conftest.py
tests/test_axis.py
tests/test_benchmark_category_axis.py
tests/test_histogram_indexing.py

This fixes a type safety issue where types could be mismatched; for example ints could be used in locators for StrCategory, when really only strings make sense.
Simplify testing a bit with a parametrized fixture (see [nice article here](https://levelup.gitconnected.com/advanced-pytest-techniques-i-learned-while-contributing-to-pandas-7ba1465b65eb)). This could probably be used elsewhere. Also improves testing output with IDs for growth.
@HDembinski, what do you think?

fix: Type safety for string index

---

.github/workflows/tests.yml
.github/workflows/wheels.yml
.travis.yml
CHANGELOG.md
src/boost_histogram/_internal/axis.py
src/boost_histogram/cpp/__init__.py
src/register_axis.cpp
tests/conftest.py
tests/test_axis.py
tests/test_benchmark_1d.py
tests/test_benchmark_2d.py
tests/test_histogram.py
tests/test_pickle.py

* CPP import now produces a warning.
* Tests use more fixtures
* Changelog updates
* Cibuildwheel update
* Partial response to #380 - categories accept all iterables.

CPP warn, update, cleanup

---

include/bh_python/axis.hpp
include/bh_python/fill.hpp
include/bh_python/register_axis.hpp
src/boost_histogram/_internal/axis.py
src/boost_histogram/axis/__init__.py
src/register_axis.cpp
tests/test_axis.py
tests/test_histogram.py

~~This will not work without https://github.com/boostorg/histogram/pull/283.~~ Edit, at @HDembinski's suggestion, converted to using axis traits everywhere and now it works without updating to latest develop.
TODO:
Boolean has not been added to cpp. (warning added to master)

feat: Add Boolean axes from Boost.Histogram

---

CHANGELOG.md
src/boost_histogram/_internal/hist.py
tests/test_histogram.py

Closes #302 - Histogram/histogram division is supported using the trick recommended by @HDembinski - the work of division is passed to the view. There are two items that need to be addressed: Accumulator views should support division if that makes sense for them, and if Unlimited is upgraded so that a view does not convert it instantly to double, then this will likely need special handling (probably triggering that conversion in this case, actually). Those are beyond the scope of this PR.
After this, we will start the process for the 0.8.0 release - the SciPy Video has already gone live.

feat: Support hist/hist division if view supports it

---

.travis.yml
pyproject.toml

Fixes a wheel build issue (we don't use NumPy's binary interface, since this is PyBind11 and not Cython, so just dropping the minimal requirement). Proper fix being worked on in https://github.com/joerick/cibuildwheel/pull/398 . Also, the timeout on Travis for ARM/PowerPC was because of the environment variable for cibuildwheel's verbose not being set, so the addition of bool fills caused this to pass 10 minutes, timing out Travis for lack of output. Now there's output while building, so it doesn't time out.

ci: Travis timeout increase

---

src/boost_histogram/_internal/hist.py

This allows dependent projects to change the axes (such as adding new features to AxesTuple, like name support in Hist), and also keeps the code a little DRYer.

feat: Allow subclasses to override axes generation

---

examples/simple_density.py
notebooks/BoostHistogramHandsOn.ipynb
setup.py
src/boost_histogram/numpy.py

NumPy warns now if something gets converted to an object array implicitly, which happens on things like prod with a list. So using the Python method here (better, anyway). Does change a common idiom shown in talks...
Also fixes `[dev]` extra missing `pytest`.

fix: warnings with NumPy 1.19

---

.gitignore
CMakeLists.txt
src/boost_histogram/_internal/hist.py
tests/test_histogram.py

Adding with a false-like, such as 0 or None, is now supported. This allows syntax like `sum(histogram_list)` without answering the hard question of what it means to add a constant to a histogram with flow bins and unevenly sized bins. That can be done much more clearly using the view or `[...] =` syntax.
Closes #261.

feat: Adding addition of 0

---

src/boost_histogram/_internal/axis.py
src/boost_histogram/_internal/hist.py
src/boost_histogram/_internal/kwargs.py
tests/test_histogram_indexing.py

This supports .metadata being propagated through the histogram, and adds `__slots__`.

feat: metadata and __slots__

---

docs/CHANGELOG.md
src/boost_histogram/_internal/hist.py
src/boost_histogram/numpy.py
tests/test_internal_histogram.py
tests/test_numpy_interface.py

`to_numpy(dd=True)` now provides `np.histogramdd` return syntax, and `bh.numpy.histogramdd` now uses it to produce the correct histogramdd result structure.

fix: NumPy syntax now handles dd

---

src/boost_histogram/_internal/axis.py
src/boost_histogram/_internal/hist.py

Slightly more helpful if you mix up indices; this way you know a bit more about the str/int that was failing.

fix: nicer error message for indexing failures

---

CONTRIBUTING.md
examples/simple_density.py
notebooks/BoostHistogramHandsOn.ipynb
src/boost_histogram/_internal/axistuple.py
tests/test_axes_object.py

@HDembinski , this is what my suggestion in #412 would look like. There are two possible methods. The first commit simply adds `.T`. The second commit allows any `np.array` action to operate on the tuple. So `h.axes.edges.ravel()` is also valid. (or `.flatten()`, but that always makes a copy). Tab completion still works in IPython (just not static typing). This feels just like the AxesTuple itself, actions are applied to each item in the tuple.

feat: allow quick transpose of all results

---

src/boost_histogram/_internal/hist.py
tests/test_histogram_init.py

Input to Histogram is a little unfriendly (passing None not identical to no keyword), will not adapt well to Python 3 signature when 2 is dropped. Fixing this also allows a small simplification.

refactor: nicer input handling

---

include/bh_python/kwargs.hpp
src/boost_histogram/_internal/hist.py
tests/test_histogram.py
tests/test_pandaslike.py

Fix #380 and add test.
Also converts `.fill` to kwargs, raises correct error now.

fix: pandas weights/samples, TypeError for extra kwargs

---

src/boost_histogram/_internal/hist.py
tests/test_histogram.py

Fix for actual issue in #431. (still need info from @jpivarski as to why a lock is in Histogram metadata, but now simple operations do shallow copies, which was the original intent).

fix: ops do shallow copy

---

src/boost_histogram/_internal/axistuple.py
tests/test_histogram.py

NumPy unconditionally calls matching named attrs when reducing. This restores the old behavior when reducing, _and_ still gets rid of the warning that occurs in NumPy 1.19 if this was just a raw Tuple. Also filters `_*` attributes, so we don't trigger anything surprising.
Note that we changed to the correct Python reductions recently, due to the warning, which is why the tests didn't catch that they completely fail in 0.10.0, rather than just showing a warning. But now we are able to fix the warning, too.
TLDR: `np.prod(x)` calls `x.prod()`, so that needs to be handled differently.
TODO: Add tests

fix: support reductions again

---

docs/CHANGELOG.md
src/boost_histogram/_internal/view.py
tests/test_views.py

Fix for comment in #431 by @colizz; expands NEP 13 support for WeighedSum View. Scalars like `WeighedSum()` are now supported too!

fix: view ops correctly supported on WeightedSum View

---

src/boost_histogram/_internal/axistuple.py
src/boost_histogram/_internal/hist.py
tests/test_histogram.py

There was an issue when applying a NumPy scalar to a histogram, brought up in, and fixes #435. I've improved the error message, avoid returning object array from reductions (making reductions on ArrayTuples useful), and fixed the 0 dimensional scalar (the actual problem in #435).

fix: array division issues

---

.pre-commit-config.yaml
docs/CHANGELOG.md
setup.cfg
src/boost_histogram/_internal/hist.py

For #437. Won't close that issue until 0.10.2. @HDembinski should we push a quick 0.10.2 with just this fix? Or should we wait a little to see if anything else comes up? The printing when filling is really irritating (though it is just an irritant).
I'm still looking into this to see if there's a good way to detect this in tests or pre-commit for the future (0.7.0 had the same issue in a different place). Edit: Now we have CI and pre-commit ensuring this never happens again!

fix: drop fill print statement

---

.github/workflows/wheels.yml
pyproject.toml

Running cibuildwheel creates a dirty git directory on Windows.
Manually triggered an upload for the missing 0.10.2 Windows wheels, this should should workaround and watch for this problem again. Issue raised upstream, too. https://github.com/joerick/cibuildwheel/issues/421

ci: winwheel dirty directory bug

---

src/register_accumulators.cpp
tests/conftest.py

I was doing
```cpp
py::object weight =py::cast<py::none>(kwargs["weight"]);
```
which happened to work on CPython and not PyPy; but it is nonsense and is now fixed. Pybind11 master now has `py::kwonly`, which sounds fantastic. :)

fix: discovered by PyPy

---

src/boost_histogram/_internal/hist.py
tests/test_histogram.py

This should both fix the linked issue, as well avoid an extra copy when the dtype is non-matching and the array is non-contigious. Pybind11 makes a copy if either of those are not true; but we were making a copy here but keeping the dtype, possibly making two copies.
Closes #452.

fix: scalar failed in ND fill

---

.clang-tidy
.github/workflows/tests.yml
CMakeLists.txt
CONTRIBUTING.md
include/bh_python/array_like.hpp
include/bh_python/axis.hpp
include/bh_python/histogram.hpp
include/bh_python/kwargs.hpp
include/bh_python/register_histogram.hpp
include/bh_python/regular_numpy.hpp
include/bh_python/transform.hpp
setup.cfg

Adding some clang-tidy checks. Making the failure if Python dependencies are not found a warning instead of an error, since it is still valid to build the source without them (such as for clang-tidy, testing a new compiler, etc).

style: clang-tidy checks

---

.github/labeler.yml
.github/workflows/pr.yml
include/bh_python/transform.hpp
setup.cfg

Quotes get (incorrectly) added to the METADATA file. Adds one small cleanup, and adds a labeler that adds a needs changelog label on any PR that doesn't have a change to the changelog.

chore: cleanup and labeler

---

.pre-commit-config.yaml
MANIFEST.in
docs/conf.py
docs/notebooks/BoostHistogramHandsOn.ipynb
docs/notebooks/PerformanceComparison.ipynb
docs/notebooks/SimpleExample.ipynb
docs/notebooks/ThreadedFills.ipynb
docs/notebooks/aghast.ipynb
docs/notebooks/xarray.ipynb
docs/requirements.txt
setup.cfg

Closes #458 
Issue discovered in https://github.com/joerick/cibuildwheel/issues/437 ; this is a workaround for us - the correct fix likely is not even in cibuildwheel, but in whatever makes the copy during the building (pip? pep517? wheel?)

ci: fix Win PyPy and Py2 builds

---

.github/workflows/tests.yml

We can unpin after the issue in GHA is fixed. See actions/setup-python#171

ci: work around broken PyPy

---

docs/CHANGELOG.md
src/boost_histogram/_internal/hist.py
src/boost_histogram/_internal/view.py
src/register_accumulators.cpp
tests/test_views.py

The view support has been refactored to allow setting with arrays on all storages, rather than just Weight() as implemented in #375. This also moves the code for supporting this directly to the view, simplifying the histogram and avoiding custom checks for storages. This uses the actual constructor from Boost.Histogram, so it avoids the internal Boost.Histogram data structure being required/exposed for Uproot 4 making TProfiles. Also fixed a bug with a missing `const` that kept the WeightedMean conversion from working for non-scalars (non-const cannot be vectorized).
Note that the histogram is now directly settable too, since it sends the request on to the view. This was manually patched in for Weight storage, but now it is properly implemented for all storages via the View.
Will be very …

feat: settable accumulator storage views

---

src/boost_histogram/tag.py
tests/test_histogram_indexing.py

Fixes #478 
* updated boostorg/histogram to latest develop with bug-fix
* added test
* Updated the rest of boost to 1.75
The core bug is fixed in boostorg/histogram, but there still seems to be a bug when `bh.loc` is used and the value is past the upper end of the axis. The computed index then should be size + 1 to make the crop work correctly.

fix: slicing projection with one-sided slices

---

src/boost_histogram/_internal/view.py
tests/test_storage.py

Fixes #486. Thanks to @alexander-held for testing the latests develop branch!
If I had static types here, I would have seen that ind could be a string, which probably would have kept me from making this mistake. But I might be giving myself too much credit there...

fix: access getitem via string was broken (and attr access uses this too)

---

docs/CHANGELOG.md
src/boost_histogram/_internal/axestuple.py
src/boost_histogram/_internal/axis.py
src/boost_histogram/_internal/hist.py
tests/test_axis.py
tests/test_subclassing.py

This removes the whole facade and just really makes this a `__dict__` class. You can now manipulate __dict__ directly, it's completely natural, and C++ just caries a pointer to it. If you need to clear the dict, set it, etc., you can.

feat: __dict__ major simplification

---

.github/workflows/tests.yml
.github/workflows/wheels.yml

While this is only a minor simplification (bundling two steps into one), it is a huge maintenance relief - we can now use GitHub's dependabot to keep us up to date on new releases (and insync in the tests & wheel files, which was not in sync before)!

ci: cibuildwheel action, bump to v1.7.3

---

.github/workflows/tests.yml
.github/workflows/wheels.yml

This should add universal2 wheels to the build matrix. ~~We won't advertise them until they have been tested on an Apple Silicon machine, but we can see if we can produce them. ;)~~ Nevermind, thanks to some fantastic testing by @chrisburr , these are vetted. Initial performance testing look _very_ promising! :)

ci: support Universal2 wheels

---

.github/workflows/tests.yml
CMakeLists.txt
include/bh_python/register_axis.hpp
setup.py

Fix #501
Support setting C++ mode in setuptools or CMake. Use the CMake naming for parallel threading. CPython 3.8 compiles in C++17 mode.
Not bothering to fix Travis because I'll be dumping it in #474 and want to avoid the merge conflict. The Conda recipe will need an update, though.

feat: allow build system to be set to C++17, rename multithread var

---

docs/CHANGELOG.md
src/boost_histogram/_internal/hist.py
tests/test_histogram.py

Just a small part of #503 - this is the only previously deprecated part.

chore: drop deprecated .rank

---

src/boost_histogram/_internal/hist.py
src/boost_histogram/numpy.py
tests/test_internal_histogram.py

This closes #413, with a proposal I made in scikit-hep/uproot3#511 - we match uproot4 by default, returning normal NumPy histogram output from `to_numpy()` on all storages. If the full view is required, a `mode="view"` can be passed. In boost-histogram 1.0, this will be type checked by MyPy. An expression like this:
```python
mplhep.histplot(h.to_numpy())
```
will no longer crash if `h` is not backed by a simple storage. Of course, since mplhep supports PlottableProtocol now, there's no need to call `to_numpy`, but other classic interfaces out of our control still use this. Including Uproot3 writing.
I've also added clarification to the docstring that `to_numpy` is not a replacement for calling `h.axes.edges()`; `to_numpy` returns the actual NumPy edges, not the boost-histogram ones, …

feat: to_numpy matching uproot, extra mode

---

src/boost_histogram/_internal/hist.py

Pulled the change out from #475 so that it can get a proper discussion if it needs it.
Boost-histogram already supports casting - you can call `Hist(a_boost_object)`, where Hist is any boost-powered project, including Hist, and it converts. Likewise with `Histogram(a_hist_object)` . This allows uproot to participate - you can call `bh.Histogram(an_uproot_histogram)` and it converts by first calling `to_boost`, then using the standard mechanism to convert it to `bh.Histogram` (or Hist, or any other dependent project if more get added).
The main question I'd like to discuss is: should we use the current method uproot provides, `.to_boost()`, or instead provide a hidden method to do this, like `_to_boost_()`, and add it to uproot? If Physt were to add a method, I bet Jan would be fine with …

feat: support _to_boost_

---

docs/CHANGELOG.md
src/boost_histogram/__init__.py
src/boost_histogram/_internal/axis.py
src/boost_histogram/_internal/axis_transform.py
src/boost_histogram/_internal/hist.py
src/boost_histogram/_internal/storage.py
src/boost_histogram/_internal/utils.py
src/boost_histogram/utils.py
tests/test_axis.py
tests/test_minihist_title.py
tests/test_subclassing.py

This is a much simpler to use family system. As a reminder, the old method (developed in #200, and which @HDembinski was still rightfully a little unhappy about in #456) is shown here:
```python
CUSTOM_FAMILY = object()
@bh.utils.set_family(CUSTOM_FAMILY)
class Hist(bh.Histogram):
...
```
This requires that you know about the magic decorator when you subclass Histogram, and if you forget it, there's no warning, you just don't convert to the right Python class from C++ all the time.
Now that we are Python 3.6+, we can support a much better system! Here it is:
```python
import hist
class Hist(bh.Histogram, family=hist):
...
```
There are two key changes. First, by making this a class keyword, this is now a missing "family" error if you do not set a family when subclassing! And, second, we …

feat: new simpler Python 3.6+ family usage

---

.github/workflows/tests.yml
.pre-commit-config.yaml
CONTRIBUTING.md
README.md
docs/usage/analyses.rst
docs/usage/histogram.rst
docs/usage/indexing.rst
docs/usage/quickstart.rst
docs/usage/storage.rst
docs/usage/transforms.rst
setup.cfg

Working on some docs cleanup and updates. So far:
Updated the readme quite a bit, making the cheatsheet unexpanded by default, and highlighting other integrations a bit more (hist, mplhep, uhi).
Reformatted some of the examples in the docs to use Black. Some areas (like the indexing page) are already carefully formatted, so it's just a manual hook for now.
TODO:
* Point at the UHI docs instead of repeating them, to reduce duplication
* Reduce duplication a bit, period - the same information shows up in a couple
of places. It's hard to avoid some duplication with the README unless we
reformat the README to rst (and even then can be tricky).

docs: update for 1.0, part 1

---

setup.cfg
src/boost_histogram/_internal/axis.py
src/boost_histogram/_internal/axis_transform.py
src/boost_histogram/_internal/hist.py
src/boost_histogram/_internal/storage.py
src/boost_histogram/numpy.py

This almost statically types the python files. Remaining:
* get/setitem for hist
* Storage needs cpp types
I'll need to add CPP stubs, mostly for filling in Accumulators (which are directly exposed) and Storages (which are subclassed but mostly exposed). Will like need "Any" defs at least for all other C++ parts. StubGen from MyPy now directly supports PyBind11, but PyBind11 types are rather poorly matched to MyPy.
- chore: adding more mypy types, axis passes --strict
- chore: adding more mypy types, hist almost passes --strict
- chore: types, almost passes --strict

types: still more

---

docs/CHANGELOG.md
docs/usage/subclassing.rst
src/boost_histogram/_internal/axis.py
tests/test_axis.py

Restore metadata in all the reprs, as requested by @HDembinski a while back. Now that we have a way to store "long" metadata (not nice to print) via `__dict__`, showing metadata= isn't a problem. It was partially shown before, but was missing on some axes types (category and boolean, at least). This also provides a more structured method for building the repr, and is clearly named to indicate that Hist is using it too.
- fix: metadata repr restored
- refactor: use more consistent name

fix: restore metadata in repr

---

setup.cfg
src/boost_histogram/version.pyi

This drops an "unused" flag in setup.cfg, but better yet supports downstream projects accessing the version too.

chore: support version in mypy

---

docs/CHANGELOG.md
src/boost_histogram/_internal/hist.py
src/boost_histogram/_internal/typing.py

See #525. Ellipsis was missing from typing support.
- fix(types): support ellipsis in get/set
- fix(types): support ellipsis in View

fix(types): ellipsis support

---

docs/CHANGELOG.md
src/boost_histogram/_internal/hist.py
src/boost_histogram/_internal/view.py

See #527. This improves the return type for `.view()`, and helps with the typing of views.

fix(types): better typing for view returns

---

docs/CHANGELOG.md
docs/usage/subclassing.rst
src/boost_histogram/_internal/hist.py
tests/test_subclassing.py

Allows `=None` for family, and makes that the default - only for Histogram. If you
subclass any further components, that requires a family for all components. This should
make subclassing _just_ Histogram easier, and should still push users to implement
families if they subclass any other components.
Better parity with 0.x series; a module that _just_ subclasses Histogram can now work with either version.

fix: allow Histogram-only subclassing to be simpler

---

docs/CHANGELOG.md
include/bh_python/accumulators/mean.hpp
include/bh_python/accumulators/weighted_mean.hpp
include/bh_python/register_accumulator.hpp
tests/test_accumulators.py
tests/test_storage.py

Closes #531, implements https://github.com/boostorg/histogram/pull/308 .
Also fixes WeightedMean. Needs backport. Also supporting `__add__` on accumulators from the Python side since that's easier to test and work with in Python.
I'm thinking releasing 1.0.1 / 0.13.1 after this sounds like a good idea.

fix: Mean/WeightedMean accumulator addition fix

---

docs/conf.py
docs/requirements.txt
setup.py

A direct switch seems to be trivial. CC https://github.com/readthedocs/recommonmark/issues/221

docs: convert recommonmark to myst-parser

---

setup.py

docs require sphinx_book_theme==0.38.0, but this version is not out as the newest is 0.1.0. I assume it's a typo and 0.0.38 was meant (which exists).
Fixed in the setup.py.

fix possible typo in sphinx_book_theme requirement

---

docs/CHANGELOG.md
src/boost_histogram/_internal/hist.py
src/boost_histogram/_internal/view.py
src/register_algorithm.cpp
tests/test_views.py

Closes #555. Added two more small changes to this PR.

fix: scaling, add logging, fix internal repr

---

docs/CHANGELOG.md
src/boost_histogram/_internal/hist.py
tests/test_histogram_indexing.py

Closes #574.
This could be expanded to support picking a set, but then the axes computations become more complex - we have to propagate metadata manually, and we have to manually handle (the) flow bin. Would be nicer with upstream support for picking. :)

fix: slicing supports under/overflow

---

.pre-commit-config.yaml
examples/cpp/CMakeLists.txt
examples/cpp/simple.cpp
tests/test_axis.py
tests/test_histogram.py

- fix: add a little extra testing for repr and empty axes
- chore: supply a little helper for checking C++ boost-histogram

chore: example of Boost.Histogram build for quick testing

---

src/boost_histogram/_internal/hist.py
tests/test_histogram.py
tests/test_histogram_indexing.py

Closes #579.
This was an intentional design decision, based on the fact that `h + 1` shouldn't add 1 to the flow bins, but scaling makes more sense to apply to all.

fix/feat: support scaling flow bins

---

src/boost_histogram/_internal/axis.py

The error message in \_\_getattr\_\_ had `not` instead of `no`.

fix: improve __getattr__ error message

---

.github/workflows/tests.yml
.github/workflows/wheels.yml
pyproject.toml

Pulling out the working bit from #583. Due to better PyPy support in the 2.x series, this should be superior already to what we have now.

ci: use CIBW 2.0 config, Python 3.10 beta testing

---

docs/usage/indexing.rst
src/boost_histogram/_internal/hist.py
tests/test_internal_histogram.py

Followup to #576, supporting sequences of bin numbers for categorical axes (needs more tests).

feat: support selecting on categorical axes (experimental)

---

src/boost_histogram/_internal/hist.py

fix(types): support typing if storage= is not passed

---

docs/usage/storage.rst

Change `storage` to `storages` in [storages.rst](https://github.com/scikit-hep/boost-histogram/blob/develop/docs/usage/storage.rst).

docs: fix typo in Storages

---

.github/workflows/wheels.yml

Missing, discovered in #609. Will build 1.1.0 locally with cibuildwheel's 2.0 config ability and upload.

ci: restore missing manylinux2010 jobs

---

docs/usage/histogram.rst

I think it should be the method `values`, not `value` (typo)
Removed a "be" (too much, typo?)
Also named value -> values (variances) to be consistent (it's also counts and not count). If you dislike this changes, I'll revert them

Minor typo fix

---

docs/CHANGELOG.md
src/boost_histogram/_internal/axestuple.py
src/boost_histogram/_internal/utils.py
tests/test_minihist_title.py

Fixes an issue we are having to work around in https://github.com/scikit-hep/hist/pull/288 .
The default setter now fails if the iterable is of the wrong length.

fix: support getattr in custom AxesTuple subclasses

---

docs/CHANGELOG.md
src/boost_histogram/_internal/axis.py
tests/test_axis.py

Closes #626 
(I removed the type: ignore as mypy complained, if that was needed for something, I'll add it back)

fix: return False if axis do not support protocol instead of raising

---

include/bh_python/accumulators/ostream.hpp
include/bh_python/histogram.hpp
include/bh_python/register_histogram.hpp
include/bh_python/storage.hpp

Adapting to the new count implementation.

chore: update Boost.Histogram to 1.77

---

docs/CHANGELOG.md
include/bh_python/register_histogram.hpp
include/bh_python/storage.hpp
src/boost_histogram/_internal/hist.py
src/boost_histogram/_internal/view.py
tests/conftest.py
tests/test_histogram.py
tests/test_views.py

Basic implementation for #632.
TODO:

feat: add boilerplate sub implementation

---

docs/CHANGELOG.md
src/boost_histogram/_internal/hist.py
tests/test_benchmark_category_axis.py

Helps with #644. Ideally, I think the order of picking and slicing should be flipped, which would probably be faster. Empty reduce should still be swapped for a copy, though, so this code code is still needed even in that case.

fix: faster picking when no slices are made

---

docs/CHANGELOG.md
pyproject.toml
src/boost_histogram/_core/algorithm.pyi
src/boost_histogram/_internal/hist.py
src/register_algorithm.cpp

This is a followup to #645, and closes #644. Benchmarks:
Before:
```
---------------------------------------------------------------------------------------------- benchmark 'Pick': 2 tests ----------------------------------------------------------------------------------------------
Name (time in us)               Min                     Max                    Mean                 StdDev                  Median                    IQR            Outliers         OPS            Rounds  Iterations
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
test_pick_only             469.6110 (1.0)       10,963.2400 (1.0) …
```

fix: faster picking when slices are made

---

docs/usage/accumulators.rst
docs/usage/histogram.rst

docs: mention stacked setting for histograms

---

docs/CHANGELOG.md
tests/test_histogram.py

Fixed upstream in https://github.com/boostorg/histogram/pull/334, closes #589.

fix: growth with single value

---

.github/workflows/tests.yml
.pre-commit-config.yaml
include/bh_python/make_pickle.hpp

Seeing if pre-commit.ci supports this.

chore: use pip instead of docker for clang-format

---

docs/CHANGELOG.md
src/boost_histogram/_internal/axestuple.py
tests/test_axes_object.py

Closes #678.
Adding the check actually helped us, too - `.metadata` was incorrectly
returning an `AxesTuple` instead of a `tuple`, and there was an extra unneeded
`AxesTuple` construction.

fix: strict AxesTuple constructor

---

.github/workflows/tests.yml
noxfile.py
pyproject.toml
src/boost_histogram/__init__.py
src/boost_histogram/_internal/axestuple.py
src/boost_histogram/_internal/axis.py
src/boost_histogram/_internal/axis_transform.py
src/boost_histogram/_internal/deprecated.py
src/boost_histogram/_internal/hist.py
src/boost_histogram/_internal/utils.py
src/boost_histogram/_internal/view.py
src/boost_histogram/accumulators.py
src/boost_histogram/numpy.py
src/boost_histogram/tag.py

Quick outline of the changes inspired by pylint:
* Use f-strings everywhere possible
* Use guard-style everywhere (simpler control flow)
* Minor import cleanup
* Cleanup of some reused and redefined variables

chore: add pylint

---

.github/workflows/tests.yml
CMakeLists.txt
docs/CHANGELOG.md
include/bh_python/register_axis.hpp
noxfile.py
tests/test_axis.py

Category indexing will return `len(index)+1` for missing index, which creates messy error messages down the line.
This should catch it correctly
Closes #387.

fix: protect Cat indexing from missing values

---

src/boost_histogram/_internal/view.py
tests/test_views.py

feat: support cumsum on weighted views

---

src/boost_histogram/_internal/hist.py
tests/test_storage.py

Brought up on Gitter. The old calculation could not have been right, and was not what is described above from the UHI.

fix: wrong calculation for WeightedMean variance NaN's via UHI

---

pyproject.toml

On PyPy, linux only, there is a UserWarning on NumPy import. This _breaks_ pytest when warnings are turned into errors, even if you ignore this one, becuase it happens in the conftest.py.
```
>>>> import boost_histogram as bh
/opt/_internal/pypy3.8-7.3.7/lib/pypy3.8/site-packages/numpy/core/_add_newdocs.py:2826: UserWarning: add_newdoc was used on a pure-python object <bound method __class_getitem__ of <class 'numpy.ndarray'>>. Prefer to attach it directly to the source.
add_newdoc('numpy.core.multiarray', 'ndarray', ('__class_getitem__',
/opt/_internal/pypy3.8-7.3.7/lib/pypy3.8/site-packages/numpy/core/_add_newdocs.py:6128: UserWarning: add_newdoc was used on a pure-python object <bound method __class_getitem__ of <class 'numpy.dtype'>>. Prefer to attach it directly to the source. …
```

fix: pypy tests fail

---

tests/test_benchmark_1d.py
tests/test_benchmark_2d.py
tests/test_histogram.py

Applied in https://github.com/conda-forge/boost-histogram-feedstock/pull/40. Working around https://github.com/numpy/numpy/issues/21062. Two more minor issues worked around.

tests: run on ppc64le without errors

---

include/bh_python/register_histogram.hpp
src/boost_histogram/_internal/hist.py
tests/test_histogram.py

Important fix, requiring 2.3.1.
Nicer error message and avoids catching a C++ error if possible.

fix: regression in #662 causing segfaults

---

.pre-commit-config.yaml

See https://github.com/psf/black/issues/2964 for details.
Committed via https://github.com/asottile/all-repos

fix: bump black to 22.3.0 due to click 8.1 release\n\nSee https://github.com/psf/black/issues/2964 for details.

---

docs/changelog.md
src/boost_histogram/numpy.py
tests/test_numpy_interface.py

Addressing half of https://github.com/scikit-hep/hist/issues/393. The other half (NaN's) is the expected behavior, and can be handled in uproot-browser.

fix: match zero range numpy quirk

---

docs/user-guide/subclassing.rst

Add missing underscores and correct typo

docs: fix typos in subclassing.rst

---

README.md

Update link for `CONTRIBUTING.md` that was moved in #723

docs: fix link in README.md

---

.pre-commit-config.yaml
pyproject.toml
src/boost_histogram/_internal/axestuple.py
src/boost_histogram/_internal/axis.py
src/boost_histogram/_internal/hist.py
src/boost_histogram/_internal/typing.py
src/boost_histogram/_internal/view.py
src/boost_histogram/numpy.py

- chore: update typing to numpy 1.22
- chore: more strict typing

chore: bump numpy used for typing

---

src/boost_histogram/_internal/view.py

Discovered minor improvements when preparing teaching material for next week.

fix: minor optimizations for ufuncs

---

README.md
src/boost_histogram/_internal/hist.py

Closes https://github.com/scikit-hep/boost-histogram/issues/567.
Although I added another operation initially, doing that just creates more confusion (two differently named functions that do exactly the same thing). So now it's simply a doc change.

reset() documentation issue

---

.github/workflows/tests.yml
.github/workflows/wheels.yml
README.md
src/boost_histogram/_core/hist.pyi
src/boost_histogram/_internal/hist.py
tests/test_internal_histogram.py
tests/test_pickles.py
tests/test_storage.py
tests/test_subclassing.py

Addresses issue faced while solving https://github.com/scikit-hep/boost-histogram/issues/157 issue.
Simply added a call function that returns storage type.
This is also needed to correctly create an empty copy an arbitrary histogram:
```python
new_hist = bh.Histogram(*old_hist.axes, storage=old_hist.storage_type())
```
Backward compatibility shim needed for a few releases since things like Hist already are having to use this; it needs to be officially public API.

Storage function to fetch storage type

---

src/boost_histogram/_internal/hist.py

Addresses https://github.com/scikit-hep/boost-histogram/issues/734 issue.
Added better error message for
- empty sample
- incompatible type sample
- incorrect dimension sample

Better error for empty AND incorrect sample

---

src/boost_histogram/_internal/hist.py

As _storage_type has changed to storage_type, accessing the previous one still works (backward compatibility) but raises a deprecation warning as suggested by @HDembinski [here](https://github.com/scikit-hep/boost-histogram/pull/781#discussion_r953496647).

Added DeprecationWarning for storage type

---

noxfile.py
src/boost_histogram/_internal/hist.py

Let's adjust this warning a bit so we can make a 1.3.2 release. It will be reverted to a full deprecation warning when 3.6 is dropped for 1.4 development.
- chore: fix hist downstream check in nox
- fix: PendingDep warning for Python 3.7 + _storage_type

fix: pending deprecation warning

---

.github/workflows/tests.yml

Committed via https://github.com/asottile/all-repos

ci: update to Python 3.11 final

---

setup.py

Resolves #822
Required if building on 32-bit Raspberry Pi. c.f. https://github.com/piwheels/packages/issues/341
Note from the [setuptools v65.6.3 docs](https://setuptools.pypa.io/en/stable/userguide/ext_modules.html#compiler-and-linker-options) 
> The linker options appear in the command line in the following order:
>
> * first, the options provided by environment variables and sysconfig variables,
> * then, a -L option for each element of Extension.library_dirs,
> * then, a linker-specific option like -Wl,-rpath for each element of Extension.runtime_library_dirs,
> * finally, the options provided by Extension.extra_link_args.
Here `extra_link_args` is used as this seems the most straightforward.

feat: Add -latomic link arg for armv7l machines

---

include/bh_python/array_like.hpp
include/bh_python/make_pickle.hpp
include/bh_python/register_axis.hpp

This should fix the weekly job checking development branches. `<boost/histogram/detail/span.hpp>` has disappeared in the same release `<boost/core/make_span.hpp>` was added - we can just not depend on either.

chore: prepare for 1.82

---

setup.py

Fixed while working on something else; new(ish) feature in pybind11.

fix: better error messages for C++ failures

---

.github/workflows/tests.yml
.github/workflows/wheels.yml
README.md

NumPy doesn't support 32-bit linux, so let's drop it too. Can be manually built if someone really needs it, or we can restore it if it causes problems. But pretty sure it won't.
Should drop the slowest CI test from 10 minutes to 6 minutes.

ci: drop 32-bit linux

---

.github/workflows/emscripten.yaml
.pre-commit-config.yaml

See https://github.com/scientific-python/cookie/pull/200.
Committed via https://github.com/asottile/all-repos

chore: ruff moved to astral-sh

---

docs/user-guide/storage.rst
include/bh_python/fill.hpp
tests/test_histogram.py
tests/test_internal_histogram.py

Fix #843.
Currently, only single fills error when using a float on an int axis - this expands the error to arrays too. It's important to error since `-.9` and `.9` both become 0 when converting from floats to ints. And explicit is better than implicit.

fix: (better) error when filling an int with a float

---

.gitattributes
docs/changelog.md

docs: prepare for 1.4.0

---

.pre-commit-config.yaml
pyproject.toml

chore: modernize Ruff

---

.github/workflows/wheels.yml
pyproject.toml

ci: more tests and win32 3.12 wheel

---

.github/labeler.yml
.github/workflows/tests.yml
noxfile.py
pyproject.toml

ci: update jobs and noxfile

---

.github/workflows/wheels.yml
.pre-commit-config.yaml

* Add generation of GitHub artifact attestations to built sdist and wheel before upload.
c.f.:
- https://github.blog/2024-05-02-introducing-artifact-attestations-now-in-public-beta/
- https://docs.github.com/en/actions/security-guides/using-artifact-attestations-to-establish-provenance-for-builds
* Update `python-jsonschema/check-jsonschema` pre-commit hook to recognize `attestations` `permissions` key.

ci: Add GitHub artifact attestations to package distribution

---

.github/workflows/emscripten.yaml
pyproject.toml

I expect this to fail. (Okay, not _that_ early!)

ci: bump to Pyodide 3.12

---

.github/workflows/emscripten.yaml
pyproject.toml

Try https://github.com/pypa/cibuildwheel/pull/1456.

ci: try cibuildwheel pyodide

---

.github/workflows/tests.yml
.gitignore
noxfile.py
pyproject.toml
src/boost_histogram/__init__.py
src/boost_histogram/version.pyi

Just a few small things, using scikit-build-core 0.10 now, move to generating the version file for the wheel only.

chore: minor touchup

---

.gitmodules
src/boost_histogram/__init__.py
src/boost_histogram/_internal/hist.py
src/boost_histogram/tag.py
tests/test_histogram.py
tests/test_histogram_indexing.py

XRef #208 
The current interface:
```python
In [1]: import numpy as np
...: 
...: import boost_histogram as bh
...: 
...: h = bh.Histogram(bh.axis.Regular(10, 0, 1))
...: h.fill(np.random.normal(size=1_000_000))
...: rebin = bh.tag.Rebinner(factor=2)
...: h[::rebin]
Out[1]: Histogram(Regular(5, 0, 1), storage=Double()) # Sum: 341605.0 (1000000.0 with flow)
In [2]: rebin = bh.tag.Rebinner(groups=[1, 2, 3])
In [3]: h[::rebin]
Out[3]: Histogram(Variable([0, 0.1, 0.3, 0.6], metadata=...), storage=Double()) # Sum: 225749.0
In [4]: s = bh.tag.Slicer()
...: 
...: h = bh.Histogram(
...:     bh.axis.Regular(20, 1, 3), bh.axis.Regular(30, 1, 3),
...: bh.axis.Regular(40, 1, 3)
...: )
...: 
...: h[{0: s[:: bh.rebin(groups=[1, 2, 3])]}].axes.size
Out[4]: (3, 30, 40)
In [5]: h[{0: s[:: …
```

feat: support variable rebinning

---

.pre-commit-config.yaml
docs/changelog.md
pyproject.toml

docs: prepare for 1.5

---

.github/workflows/emscripten.yaml
.github/workflows/tests.yml
.github/workflows/wheels.yml
.pre-commit-config.yaml
CMakeLists.txt
docs/user-guide/subclassing.rst
examples/cpp/CMakeLists.txt
examples/simple_weight.py
include/bh_python/register_axis.hpp
pyproject.toml
src/boost_histogram/__init__.py
src/boost_histogram/_internal/axis.py
src/boost_histogram/_internal/hist.py
src/boost_histogram/_internal/typing.py
src/boost_histogram/_internal/view.py
src/boost_histogram/accumulators.py
src/boost_histogram/axis/__init__.py
src/boost_histogram/axis/transform.py
src/boost_histogram/numpy.py
src/boost_histogram/storage.py
src/boost_histogram/tag.py

chore: update cibw config

---

.github/CONTRIBUTING.md
docs/changelog.md
src/boost_histogram/_internal/hist.py
tests/test_storage.py

Fixes #971 
Now the code loops over every `dtype.name` if the `view()` of a `Histogram` is a structured NumPy array.

fix: make non-uniform rebinning work for `Weight()` and friends

---

src/boost_histogram/histogram.py
src/boost_histogram/tag.py
tests/test_histogram.py

- **feat: allow rebinning by passing edges (or directly a hist.axis)**
- **fix: preserve flow when rebinning**

feat: allow rebinning by passing edges or a new axis

---

docs/changelog.md
pyproject.toml
src/boost_histogram/histogram.py
src/boost_histogram/tag.py
src/boost_histogram/typing.py
tests/test_histogram.py

Followup to #977. Uses the new axes if one is provided.
I wonder if we should allow axis + other args, if someone wants to use a new axis with a custom mapping?
We'll have to work out the correct mapping for flow bins for the four cases.

fix: axis passthrough

---

noxfile.py
pyproject.toml
src/boost_histogram/view.py

Bumping to 0.11, including METADATA 2.2.

chore: bump scikit-build-core to 0.11

---

noxfile.py
pyproject.toml

chore: new nox, pytest-xdist

---

.readthedocs.yml
pyproject.toml

chore: use PEP 639 licenses (METADATA 2.4)

---

.readthedocs.yml

ci: use uv pip install --group in rtd

---

src/boost_histogram/histogram.py
src/boost_histogram/tag.py
tests/test_histogram.py

Still need to handle the one-sided flow case.

fix: allow axis + other

---

.github/workflows/tests.yml
.github/workflows/wheels.yml
README.md
docs/conf.py
examples/README.md
notebooks/BoostHistogramHandsOn.ipynb
notebooks/xarray.ipynb
pyproject.toml
src/boost_histogram/_core/axis/__init__.pyi
src/boost_histogram/_utils.py
src/boost_histogram/axis/__init__.py
src/boost_histogram/histogram.py
src/boost_histogram/numpy.py
src/boost_histogram/tag.py
src/boost_histogram/typing.py
src/boost_histogram/view.py
tests/conftest.py
tests/pickles/make_pickle.py
tests/test_pickles.py

feat: drop Python 3.8

---

.github/CONTRIBUTING.md
.github/workflows/tests.yml
CMakeLists.txt
CMakePresets.json
pyproject.toml
tests/CMakeLists.txt

chore: setup CMake presets

---

src/boost_histogram/histogram.py
tests/test_histogram_indexing.py

Fix an issue found in https://github.com/scikit-hep/uhi/pull/150; setting a range with a scalar disregards the range.

fix: setting a range with a scalar

---

src/boost_histogram/tag.py
tests/test_histogram.py

This PR fixes the rebinning of axes given a sequence of new edges that was recently added by #977.
We recently discovered the new rebinning feature that only requires new edges values rather than bin count "groups", which is great! It requires that the requested edges *coincide* (that's where the problem is) with old ones so that bin content merging is logically unambiguous. However, we ran into an edge case where a single, new edge value is subject to float precision effects (e.g. `1.200000000000001`).
Currently, this causes a bug in that the newly computed edges are missing an entry, resulting in axes dropping a bin. I extended the `test_rebin_1d` test case to use a fuzzy edge value, showing that the assertion in
https://github.com/scikit-hep/boost-histogram/blob/fdfdae17926ab8b760323e82 …

fix: Account for fuzzy edge values in rebinning with edges

---

.clang-tidy
include/bh_python/array_like.hpp
include/bh_python/fill.hpp
include/bh_python/make_pickle.hpp
include/bh_python/register_accumulator.hpp
include/bh_python/register_axis.hpp
include/bh_python/register_histogram.hpp
include/bh_python/register_storage.hpp
include/bh_python/regular_numpy.hpp
include/bh_python/storage.hpp
include/bh_python/transform.hpp
include/bh_python/vector_string_caster.hpp
src/register_accumulators.cpp
src/register_transforms.cpp

This reduces the number of refcount changes we make by quite a bit - should be especially nice on free-threaded Python. :)

chore: performance clang-tidy checks

---

.github/workflows/emscripten.yaml
.github/workflows/tests.yml
.github/workflows/wheels.yml
pyproject.toml
tests/test_pickle.py

cibuildwheel 3.0 with graalpy, linux image bumps, iOS. pybind11 3.0.

chore: bump cibw & pybind11

---

.github/workflows/tests.yml
pyproject.toml

I was originally adding subinterpreter support, but it looks like numpy doesn't support it yet. Here's some test version updates, anyway.
<details><summary>Subinterpreter attempt:</summary>
<p>
```diff
diff --git a/src/module.cpp b/src/module.cpp
index 7a6bbe2..b09086d 100644
--- a/src/module.cpp
+++ b/src/module.cpp
@@ -12,7 +12,10 @@ void register_histograms(py::module&);
void register_accumulators(py::module&);
void register_transforms(py::module&);
-PYBIND11_MODULE(_core, m, py::mod_gil_not_used()) {
+PYBIND11_MODULE(_core,
+                m,
+                py::mod_gil_not_used(),
+                py::multiple_interpreters::per_interpreter_gil()) {
py::module storage = m.def_submodule("storage");
register_storages(storage);
diff --git a/src/register_accumulators.cpp …
```

ci: update Python versions

---

src/boost_histogram/histogram.py
tests/test_serialization_uhi.py

This supports directly converting from UHI.
It also fixes a bug where the metadata keyword would get ignored on one of the paths.. We might want to combine metadata instead, but that can be a future PR. An error is thrown if storage is also passed, since it would have been ignored.
Since we now support at least 3.8 (3.9, actually, I think), we can finally fix a typing bug where the types thought it was okay to pass multiple histograms.

feat: support constructor conversion from UHI

---

src/boost_histogram/serialization/__init__.py
src/boost_histogram/serialization/_axis.py
tests/test_serialization_uhi.py

Adding unserializable metadata.
This is only for histogram serialization; which supports a limited set of values, it still gets pickled.

feat: unserializable metadata

---

src/boost_histogram/histogram.py
src/boost_histogram/serialization/__init__.py
src/boost_histogram/serialization/_axis.py
src/boost_histogram/serialization/_common.py
tests/test_serialization_uhi.py

Supporting this on Histogram, like it's already supported on Axes. Should help users find the correct way to set metadata, and is more optimal than replacing `__dict__`, as we can use the key-sharing dict in modern Pythons.
Also skip storing None, since None isn't a defined datatype in UHI.

fix: support __dict__ on histogram like axes

---

src/boost_histogram/histogram.py
src/boost_histogram/serialization/_storage.py
tests/test_serialization_uhi.py

Another fix working on hist/uhi.

fix: serialization was broken for N>1D complex storage histograms
