scikit-hep/boost-histogram

- include/boost/histogram/python/storage.hpp
- src/histogram/histogram.cpp
- src/histogram/storage.cpp
Working on some cleanup and new storage types.
> Storage and histogram cleanup

- src/histogram/axis.cpp
- src/histogram/histogram.cpp
- tests/test_axis_internal.py
- tests/test_histogram_internal.py
- tests/test_make_histogram.py
Adding direct access to axis and bin details. Metadata (labels only at the moment) has been added. An initial version of make_histogram has been added. It currently does not always select the fastest histogram impl.
> Axis and bin improvements

- include/boost/histogram/python/axis.hpp
- include/boost/histogram/python/pybind11.hpp
- include/boost/histogram/python/storage.hpp
- src/histogram/axis.cpp
- src/histogram/histogram.cpp
- src/histogram/storage.cpp
This address the comment in #11, and does a bit of cleanup.
> Henryiii cleanup

- include/boost/histogram/python/axis.hpp
- include/boost/histogram/python/histogram.hpp
- src/histogram/axis.cpp
- tests/test_axis_internal.py
- tests/test_histogram_internal.py
Accessing axis properties is vectorized where appropriate (`.update` is not vectorized yet). Now supports growing histograms and growing axis.
> Adding vectorized axis values

- .ci/azure-cmake-steps.yml
- CMakeLists.txt
- include/boost/histogram/python/axis.hpp
- include/boost/histogram/python/histogram.hpp
- src/histogram/axis.cpp
- src/histogram/histogram.cpp
Fixing a warning for macOS 10.14.4, and making warnings as errors optional (really only needed for CI).
Also adding a standard metadata type (could be changed from a string eventually).
> Henryiii macos 10.14.4

- README.md
- include/boost/histogram/python/axis.hpp
- src/histogram/axis.cpp
- src/histogram/histogram.cpp
- tests/test_axis_internal.py
- tests/test_histogram_internal.py
This one already works, no need for special fill. Also adding sum algorithm (might be expanded for `flow=False` in the future. A max algorithm might be useful too.
> Adding int category

- CMakeLists.txt
- boost/histogram_utils.py
- notebooks/PerformanceComparison.ipynb
- notebooks/performance_report.py
- src/histogram/axis.cpp
- src/histogram/histogram.cpp
- tests/test_make_axis.py
- tests/test_public_axis.py
- tests/test_public_hist.py
Testing the metaclass idea from @eacousineau.
regular is the type and constructor for `regular_*` classes.
> Add metaclass 

- include/boost/histogram/python/pybind11.hpp
- include/boost/histogram/python/storage.hpp
- include/boost/histogram/python/try_cast.hpp
- src/histogram/histogram.cpp
- src/histogram/storage.cpp
try_cast behaves somewhat like a visitor for pybind11::objects.
> introducing try_cast

- .ci/azure-build-pipeline.yml
- .ci/azure-test-pipeline.yml
> Move pipeline files

- .readthedocs.yml
- README.md
- docs/conf.py
- docs/requirements.txt
> Adding doc requirements

- scripts/check_style_docker.sh
- setup.cfg
- setup.py
@HDembinski, please see if this patch fixes your formatting becomes root-owned issue..
> Docker user and group ID fix

- .ci/azure-publish-dist.yml
- README.md
- docs/usage/quickstart.rst
- include/boost/histogram/python/axis.hpp
- include/boost/histogram/python/bin_setup.hpp
- include/boost/histogram/python/indexed.hpp
- include/boost/histogram/python/kwargs.hpp
- include/boost/histogram/python/register_accumulator.hpp
- include/boost/histogram/python/register_axis.hpp
- include/boost/histogram/python/register_histogram.hpp
- include/boost/histogram/python/register_storage.hpp
- include/boost/histogram/python/try_cast.hpp
- setup.py
- src/histogram/accumulators.cpp
- src/histogram/axis.cpp
- src/histogram/general_histograms.cpp
- src/histogram/make_histogram.cpp
- src/histogram/polymorphic_bin.cpp
- src/histogram/storage.cpp
- src/module.cpp
- tests/test_indexed.py
* Add tests ✅ 
* `boost::histogram::axis::polymorphic_bin<double>` needs wrapping ✅ 
* Can `ind.centers()`, etc be supported? ✅ 
Will close #54 .
> Adding indexed accessor

- tests/test_public_hist.py
Weighted fills are now supported, so recover the old tests.
> Unskip remaining skipped tests

- include/boost/histogram/python/axis.hpp
- include/boost/histogram/python/histogram.hpp
- include/boost/histogram/python/indexed.hpp
- include/boost/histogram/python/pickle.hpp
- include/boost/histogram/python/register_accumulator.hpp
- include/boost/histogram/python/register_axis.hpp
- include/boost/histogram/python/register_histogram.hpp
- include/boost/histogram/python/register_storage.hpp
- include/boost/histogram/python/storage.hpp
- src/histogram/accumulators.cpp
- src/histogram/general_histograms.cpp
- src/histogram/make_histogram.cpp
- src/histogram/storage.cpp
Waiting on boostorg/histogram#209. Fixes #80.
> Making includes more specific

- include/boost/histogram/python/register_storage.hpp
- tests/test_pickle.py
> Make push_back private

- .ci/azure-test-pipeline.yml
- README.md
- boost_histogram/storage.py
- include/boost/histogram/python/register_histogram.hpp
- include/boost/histogram/python/storage.hpp
- src/register_general_histograms.cpp
- src/register_make_histogram.cpp
- src/register_storage.cpp
- tests/test_pickle.py
- tests/test_profiles.py
> Rename profile -> mean

- CMakeLists.txt
- CONTRIBUTING.md
- include/boost/histogram/python/pybind11.hpp
- tests/test_benchmark_1d.py
- tests/test_benchmark_2d.py
Now checking with several different input types.
> Faster math, better support for IDEs

- .ci/azure-build-pipeline.yml
- .ci/azure-test-pipeline.yml
- .ci/build-wheels.sh
- .ci/macos-install-python.sh
- CHANGELOG.md
- README.md
Adding 3.8 to the wheels and tests.
> Adding Python 3.8

- .ci/azure-test-pipeline.yml
- MANIFEST.in
First adding a test that fails.
Will fix #153.
> Source dist problem

- include/boost/histogram/python/register_histogram.hpp
- tests/test_histogram_internal.py
> Fix strided inputs

- boost_histogram/__init__.py
- boost_histogram/_hist.py
- boost_histogram/accumulators.py
- boost_histogram/algorithm.py
- boost_histogram/axis.py
- boost_histogram/storage.py
- boost_histogram/utils.py
Cleans up tab completion in iPython.
> Less leakage

- setup.py
Followup to #162. Verify this does work in all cases.
> Even simpler listings of source files

- boost_histogram/algorithm.py
- include/boost/histogram/python/axis.hpp
- include/boost/histogram/python/axis_ostream.hpp
- include/boost/histogram/python/histogram_ostream.hpp
- include/boost/histogram/python/register_axis.hpp
- include/boost/histogram/python/register_histogram.hpp
- tests/test_public_hist.py
* Update Boost.Histogram
* Drop usage of (now missing) cat
* Drop local version of empty.
> Updating histogram to include empty

- .ci/build-wheels.sh
- .gitignore
- include/boost/histogram/python/sum.hpp
- src/register_accumulators.cpp
Also bumps BH version, and makes it easier to run YCM. Includes one fix from YCM.
The new version of BH has a change to accumulators, this is covered here.
> Add manylinux1 Python 3.8

- .ci/azure-build-pipeline.yml
- README.md
This only affects the wheel building.
> Adding Python 3.8 wheels

- include/boost/histogram/python/kwargs.hpp
- tests/test_public_hist.py
Closes #210. Adding a test, just in case it tries to sneak back in.
> Finally fixing that pesky comma

- boost_histogram/_internal/axis.py
> Fixing argument names for axis

- .gitmodules
- CMakeLists.txt
- MANIFEST.in
- setup.py
> Removing callable traits

- boost_histogram/__init__.py
- boost_histogram/_internal/axis.py
- boost_histogram/_internal/hist.py
- boost_histogram/axis/__init__.py
> Adding FutureWarning

- .clang-format
- examples/guide_mixed_cpp_python.cpp
- include/boost/histogram/python/accumulators/mean.hpp
- include/boost/histogram/python/accumulators/ostream.hpp
- include/boost/histogram/python/accumulators/weighted_mean.hpp
- include/boost/histogram/python/accumulators/weighted_sum.hpp
- include/boost/histogram/python/axis.hpp
- include/boost/histogram/python/axis_setup.hpp
- include/boost/histogram/python/histogram.hpp
- include/boost/histogram/python/kwargs.hpp
- include/boost/histogram/python/make_pickle.hpp
- include/boost/histogram/python/metadata.hpp
- include/boost/histogram/python/options.hpp
- include/boost/histogram/python/pybind11.hpp
- include/boost/histogram/python/register_accumulator.hpp
- include/boost/histogram/python/register_axis.hpp
- include/boost/histogram/python/register_histogram.hpp
- include/boost/histogram/python/register_storage.hpp
- include/boost/histogram/python/regular_numpy.hpp
- include/boost/histogram/python/storage.hpp
- include/boost/histogram/python/sum.hpp
- include/boost/histogram/python/transform.hpp
- include/boost/histogram/python/try_cast.hpp
- src/module.cpp
- src/register_accumulators.cpp
- src/register_algorithm.cpp
- src/register_axis.cpp
- src/register_histograms.cpp
- src/register_storage.cpp
- src/register_transforms.cpp
> Fix pointer alignment

- include/boost/histogram/python/register_histogram.hpp
- tests/test_histogram.py
Needs tests, but I think I've fixed #220.
> Stale axis fix

- boost_histogram/_internal/hist.py
- boost_histogram/storage.py
> Restoring warning to lower case storages

- include/array_like.hpp
- include/axis.hpp
- include/fill.hpp
- include/register_axis.hpp
- include/vector_string_caster.hpp
- tests/test_axis.py
- tests/test_benchmark_category_axis.py
Warnings: needs a rebase after #243 is merged, then will look much simpler. Do not yet review!
Pending on #243 
- ~[ ] needs implementation of index and update that does not create a temporary std::string~
> Faster category str2

- CONTRIBUTING.md
> Add release checklist

- .ci/azure-cmake-steps.yml
- .ci/azure-test-pipeline.yml
- .github/workflows/tests.yml
- README.md
Basic CMake testing (mostly) moved to actions.
> Adding more testing to actions

- .gitignore
- CONTRIBUTING.md
- tests/test_histogram_indexing.py
Addresses the bug exposed in #274, by applying the fix from https://github.com/boostorg/histogram/issues/257 .
Also continuing to work on the contributing guide.
> Fixing no flow indexing

- include/accumulators/ostream.hpp
- include/register_accumulator.hpp
- tests/test_accumulators.py
This is an initial fix for a bug that keeps Sum() from producing a repr.
And I'm not sure why it shows "Sum(0)" instead of "Sum(0 + 0)".
> Fix bug in Sum repr

- README.md
- boost_histogram/accumulators.py
- docs/api/boost_histogram.rst
- docs/index.rst
- docs/usage/accumulators.rst
- docs/usage/analyses.rst
- docs/usage/histogram.rst
- docs/usage/indexing.rst
- docs/usage/numpy.rst
- docs/usage/quickstart.rst
- docs/usage/storage.rst
> Adding new docs

- .github/workflows/examples.yml
- setup.py
GitHub Actions seems to delete old patch versions. Closes #308
> Fix CI for Python 3.8.1 replacing 3.8.0

- .all-contributorsrc
- .gitignore
- CONTRIBUTING.md
- README.md
Adding all-contributors. There's a bot too, but it seemed to not be working last I checked, so not rushing to add it.
> All contributors

- setup.cfg
- tests/pytest.ini
> Fix issue with test discovery 

- boost_histogram/_internal/hist.py
- tests/test_histogram_indexing.py
Closes #319. Slightly simpler code, too, better sharing between dict and positional access.
> Making dict access equivalent to positional

- docs/usage/quickstart.rst
Small Typo in docs. 
@henryiii
> small typo in docs

- docs/usage/indexing.rst
- docs/usage/numpy.rst
- docs/usage/storage.rst
- docs/usage/transforms.rst
@henryiii , I add some spaces to be consistent with other usage and code style. Thank You.
> Add spaces to be consistent with other usage.

- notebooks/BoostHistogramHandsOn.ipynb
- notebooks/PerformanceComparison.ipynb
- notebooks/SimpleExample.ipynb
- notebooks/ThreadedFills.ipynb
- notebooks/xarray.ipynb
@henryiii , In this PR, I modify indent of the Jupyter Notebooks. Thank You.
> Add spaces where required.

- src/boost_histogram/cpp/algorithm.py
- src/register_algorithm.cpp
- tests/test_cpp_interface.py
* updates boost.histogram to develop
* updates the reduce interface to match boost.histogram
* added a lot more tests (test coverage for reduce and friends had large holes)
> updating boost.histogram

- CONTRIBUTING.md
- README.md
- docs/conf.py
- include/bh_python/register_histogram.hpp
- src/boost_histogram/__init__.py
- src/boost_histogram/cpp/algorithm.py
After merging this, will push develop to master and tag a release (if everything builds correctly).
> Prepare for 0.7.0

- src/boost_histogram/_internal/hist.py
- tests/test_cpp_interface.py
> Add axis default like in C++ and test

- tests/test_axis.py
Neither a ToDo item or an illustration
> delete redundant comment line

- CONTRIBUTING.md
- setup.cfg
Update all libs to 1.73, add warnings when running pytest.
> Boost 1.73

- .github/workflows/tests.yml
- CMakeLists.txt
- dev-requirements.txt
- include/bh_python/register_accumulator.hpp
- include/bh_python/register_axis.hpp
- include/bh_python/register_histogram.hpp
- include/bh_python/register_storage.hpp
- pyproject.toml
- setup.cfg
- src/boost_histogram/__init__.py
- src/boost_histogram/_internal/axis_transform.py
- src/boost_histogram/_internal/hist.py
- src/boost_histogram/_internal/view.py
- src/boost_histogram/tag.py
- src/register_axis.cpp
- tests/test_histogram.py
Updating to latest BH. Now supports addition of histograms with growing categories that do not match! Using `+=` now recomputes the axes cache.
> Note: It would be nice if the axes objects could know if they are no longer pointing at a valid axes object.
MyPy used for some *very* basic checking, not tested in CI yet. Cleaned up a couple of places at its request, and fixed a few potential bugs!
> Update to latest dev histogram

- docs/usage/indexing.rst
- src/boost_histogram/_internal/hist.py
- src/boost_histogram/tag.py
- tests/test_histogram_indexing.py
This would convert to using the built-in sum. @HDembinski , can you sign off on this, just to make sure you agree to it?
When UHI is completed, any vector -> scalar function will be supported here. Rebinning generally will be even tricker, since it has to change the axes. (See #208)
> Built-in sum

- include/bh_python/register_histogram.hpp
- src/boost_histogram/_internal/axis.py
- src/boost_histogram/_internal/hist.py
Use BH's cropping. Refactor internal function a little as well.
> refactor: use BH cropping

- src/boost_histogram/_internal/view.py
- tests/test_storage.py
Basic support for #354. We could possibly expand support to other ufuncts/storages, though.
> feat: Adding ufunc support to WeighedSumView

- src/boost_histogram/_internal/hist.py
- tests/test_histogram_set.py
> feat: assign Weight() with simple arrays supported

- notebooks/aghast.ipynb
- src/boost_histogram/_internal/axistuple.py
- tests/test_histogram_indexing.py
Resolves #383.
feat: Slicing on the tuple before the method call controls the shapes of the result.
Also fills in the aghast outputs (missing previously)
> fix: AxesTuple slicing keeps type

- src/boost_histogram/_internal/hist.py
- tests/test_histogram.py
- tests/test_histogram_init.py
> feat: rank -> ndim

- src/boost_histogram/_internal/axis.py
- src/boost_histogram/_internal/hist.py
- src/boost_histogram/_internal/six.py
> fix: Allow any array-like to be used in fill

- MANIFEST.in
- README.md
- docs/CHANGELOG.md
- docs/conf.py
- docs/index.rst
- docs/requirements.txt
- docs/usage/installation.rst
Makes the CHANGELOG available in the docs, with nicer formatting.
> Nicer Changelog

- .github/workflows/tests.yml
- .github/workflows/wheels.yml
- .travis.yml
Try to fix the broken deploy on travis for 0.8.1.
> ci: Fix Travis deploy

- src/boost_histogram/_internal/hist.py
- tests/test_histogram.py
Quick fix for #395, targeting 0.8.1. May change to different system in next version.
> fix: bool pick for 2D+

- src/boost_histogram/_internal/axistuple.py
- src/boost_histogram/axis/__init__.py
> feat: provide AxesTuple in public location

- docs/usage/accumulators.rst
- include/bh_python/accumulators/weighted_mean.hpp
- src/boost_histogram/_internal/view.py
- src/register_accumulators.cpp
- tests/test_storage.py
> refactor: add _ to large, small, sum_of_weighted_deltas_squared

- include/bh_python/register_histogram.hpp
- src/boost_histogram/_internal/hist.py
- tests/test_histogram.py
This refactors operator handling, allowing operations with an array to work #416, and unifies some of the operator handling. Histogram *op* Histogram is handled by BH, all others are handled by the view.
> feat: fix operators on arrays, adds support for it

- docs/requirements.txt
- docs/usage/axes.rst
- setup.py
Fix the build (see https://github.com/executablebooks/sphinx-book-theme/issues/132). Also reduce warnings when building docs locally.
> docs: fix build

- docs/CHANGELOG.md
- src/boost_histogram/_internal/hist.py
- tests/test_histogram.py
- tests/test_histogram_indexing.py
> feat: no-slice rebin/sum

- .all-contributorsrc
- .cmake-format.yaml
- .pre-commit-config.yaml
- CMakeLists.txt
- README.md
- setup.cfg
Adding nice formatting to the CMake files, and filling in a few contributors.
> chore: CMake format

- .github/workflows/tests.yml
Pushed several updates up to the formatting plugin; now happy with the results, so ready to go in. Also updating the CI just a bit.
> ci: gha pytest plugin

- MANIFEST.in
- pyproject.toml
- setup.py
- setup_helpers.py
> refactor: pybind11 new setup, remove NumPy dist

- src/boost_histogram/_internal/axis.py
- tests/test_axis.py
Drop the metadata from the repr.
> fix: drop metadata from the repr

- .github/workflows/wheels.yml
- .pre-commit-config.yaml
- notebooks/BoostHistogramHandsOn.ipynb
- notebooks/PerformanceComparison.ipynb
- notebooks/SimpleExample.ipynb
- notebooks/ThreadedFills.ipynb
- notebooks/aghast.ipynb
- notebooks/xarray.ipynb
- tests/test_pickles.py
Includes a fix by updating Boost.Histogram, closes #468.
- docs: black formatting for notebooks
- feat: update to pybind11 2.6.1
- fix: update boost-histogram to fix inf in Variable issue
- ci: restore NumPy testing
> chore: updates

- src/boost_histogram/numpy.py
- tests/test_numpy_interface.py
> fix: support weights as NumPy array in numpy.py

- CMakeLists.txt
- docs/CHANGELOG.md
- include/bh_python/register_axis.hpp
- include/bh_python/regular_numpy.hpp
- tests/test_numpy_interface.py
> fix: support slicing NumPy axes

- src/boost_histogram/_internal/axestuple.py
- src/boost_histogram/_internal/deprecated.py
- src/boost_histogram/_internal/hist.py
- src/boost_histogram/_internal/typing.py
- src/boost_histogram/_internal/utils.py
- src/boost_histogram/_internal/view.py
- src/boost_histogram/tag.py
Adding some more static typing.
> chore: adding more mypy types

- src/boost_histogram/_internal/hist.py
- src/boost_histogram/_internal/typing.py
- src/boost_histogram/accumulators.py
- src/boost_histogram/numpy.py
- src/boost_histogram/tag.py
Collecting fixes for the typing while implementing downstream typing in Hist. Includes an actual (though _very_ rare) bug fix for the numpy module.
> types: minor fixes

- docs/CHANGELOG.md
- src/boost_histogram/_internal/hist.py
Discovered by @alexander-held in https://github.com/scikit-hep/boost-histogram/discussions/525#discussioncomment-474816
> fix(types): better typing for constructor from existing histogram

- setup.py
- tests/test_accumulators.py
- tests/test_pbt.py
Better testing for accumulators, and testing some things for profiles.
> tests: add some property based tests

- dev-requirements.txt
- tests/test_accumulators.py
> tests: add requirements to dev-requirements

- docs/CHANGELOG.md
- src/boost_histogram/_internal/axis.py
- src/register_algorithm.cpp
- tests/test_histogram_indexing.py
> fix: categorical axes need special flow handling

- setup.cfg
> tests: print out logging info on pytest failures

- docs/usage/accumulators.rst
- Add missing `"`s in [accumulators.rst](https://github.com/scikit-hep/boost-histogram/blob/develop/docs/usage/accumulators.rst)
- Update outputs in [accumulators.rst](https://github.com/scikit-hep/boost-histogram/blob/develop/docs/usage/accumulators.rst)
> docs: fix typo and output in Accumulators

- tests/test_axis.py
> tests: could fail on 32 bit archs (edge behavior)

- docs/CHANGELOG.md
- tests/conftest.py
- tests/test_histogram.py
> tests: add neg integer test

- tests/test_histogram.py
Missed this bit of Python 2 code.
> style: minor cleanup

- .pre-commit-config.yaml
Reverts scikit-hep/boost-histogram#665
> Revert "style: drop pycln"

- noxfile.py
- pyproject.toml
- setup.cfg
- setup.py
I tend to use boost-histogram as an example or a reference, so doing a bit of cleanup on best practices.
> chore: some cleanup

- noxfile.py
- pyproject.toml
> chore: nicer output from pylint

- setup.py
> fix: try local include

- docs/CHANGELOG.md
- include/bh_python/register_accumulator.hpp
- src/register_accumulators.cpp
- chore: bump to boost 1.78 & pybind11 2.9.1
- docs: prepare for 1.3.0
> chore: prepare for release

- docs/usage/axes.rst
> docs: fix minor typos in Axes

- README.md
> docs: mention other useful libraries

- .pre-commit-config.yaml
- docs/conf.py
- docs/user-guide/axes.rst
- examples/simple_2d.py
- examples/simple_pickly.py
- pyproject.toml
- src/boost_histogram/_internal/enum.py
- tests/env.py
- tests/pickles/make_pickle.py
- tests/test_histogram.py
- tests/test_pickle.py
> chore: minor mypy cleanup

- .pre-commit-config.yaml
- noxfile.py
- pyproject.toml
- src/boost_histogram/_internal/hist.py
- src/boost_histogram/_internal/view.py
- src/boost_histogram/tag.py
- fix(style): update and pin pylint
- fix: mypy fix
> fix: linter updates

- notebooks/BoostHistogramHandsOn.ipynb
> Fixed a minor broken markdown text formatting

- include/bh_python/register_axis.hpp
Support for things like Python 3.11.
> chore: update to pybind11 2.10.0

- include/bh_python/register_axis.hpp
- tests/test_histogram_indexing.py
As described in https://github.com/scikit-hep/boost-histogram/issues/737. Starting by adding a test.
> tests: add test for large num

- src/boost_histogram/_internal/hist.py
- tests/test_internal_histogram.py
> fix: support pick_set inside a larger expression

- src/boost_histogram/_internal/view.py
Might help debugging a bit - mentioned on gitter.
> fix: better error message for mismatched views

- src/boost_histogram/_internal/hist.py
Quick followup since we are on development toward 1.4.
> chore: increase deprecation level

- src/boost_histogram/_internal/axis.py
- src/boost_histogram/numpy.py
A little bit of minor cleanup.
> chore: a few suggestions from refurb

- docs/index.rst
- docs/user-guide/accumulators.rst
- docs/user-guide/analyses.rst
- docs/user-guide/axes.rst
- docs/user-guide/histogram.rst
- docs/user-guide/installation.rst
- docs/user-guide/numpy.rst
- docs/user-guide/quickstart.rst
- docs/user-guide/storage.rst
- docs/user-guide/subclassing.rst
> docs: change code directives to code-block

- .github/CONTRIBUTING.md
> docs: add nox to documentation

- .pre-commit-config.yaml
- pyproject.toml
- src/boost_histogram/_internal/view.py
- tests/test_axis.py
- tests/test_histogram.py
> chore: update numpy for mypy, 3.11 pre-commit support

- .readthedocs.yml
- docs/requirements.txt
Docs are broken, not sure why, checking ~~myst~~ nbsphinx.
> docs: update readthedocs config

- docs/api/boost_histogram.axis.rst
- docs/api/boost_histogram.rst
- docs/conf.py
- noxfile.py
Also adding a nox job to make it easier to do in the future.
> docs: rebuild API docs

- .clang-format
- .clang-tidy
- .github/CONTRIBUTING.md
- .github/labeler.yml
- .github/workflows/emscripten.yaml
- .github/workflows/examples.yml
- .github/workflows/pr.yml
- .github/workflows/tests.yml
- .github/workflows/weekly.yml
- .github/workflows/wheels.yml
- .pre-commit-config.yaml
- .readthedocs.yml
- README.md
- docs/banner_slides.md
- docs/changelog.md
- examples/README.md
Controlled formatting of some more files & basic validity checking.
> style: add prettier

- .pre-commit-config.yaml
- README.md
- docs/banner_slides.md
- docs/changelog.md
- docs/conf.py
- docs/index.rst
- docs/user-guide/axes.rst
- docs/user-guide/numpy.rst
- docs/user-guide/subclassing.rst
- docs/user-guide/transforms.rst
- noxfile.py
Fixes a few things too, like random ":noindex:" in the outout, discovered by making sure the Python blocks are, in fact, Python.
> style: add blacken docs

- CMakeLists.txt
- include/bh_python/pybind11.hpp
Will need to fix the locking around metadata soon.
> chore: update pybind11

- .github/workflows/wheels.yml
- README.md
- pyproject.toml
- setup.cfg
> ci: fix wheel build for 3.12

- .github/CONTRIBUTING.md
- CMakeLists.txt
- tests/CMakeLists.txt
Some cleanup pulled out of #887.
> chore: cleanup CMake a bit

- .github/workflows/tests.yml
- noxfile.py
- tests/conftest.py
> fix: support NumPy 2

- .github/workflows/wheels.yml
- .pre-commit-config.yaml
> ci: trusted publisher

- .pre-commit-config.yaml
- pyproject.toml
Remove a few files from the SDist to shrink it a bit more like before.
> chore: clean up sdist a bit

- .github/workflows/emscripten.yaml
- pyproject.toml
First just bumping the version.
> ci: try to fix pyodide build

- .github/workflows/emscripten.yaml
- .gitignore
- include/bh_python/histogram.hpp
- pyproject.toml
> ci: update emscripten build

- .github/workflows/tests.yml
Testing out some possible speedups.
> ci: try out possible speedups

- .github/workflows/tests.yml
- .github/workflows/wheels.yml
- .pre-commit-config.yaml
- pyproject.toml
> ci: faster cibuildwheel

- .github/workflows/tests.yml
- .gitignore
- CMakeLists.txt
- pyproject.toml
- src/module.cpp
Trying out free-threaded Python.
> feat: support Python 3.13t

- .github/workflows/tests.yml
- pyproject.toml
> ci: adapt to final release of NumPy 2.1.0

- .github/workflows/wheels.yml
> ci: restore missing wheels

- pyproject.toml
Quite a few of these are fixed now.
> chore: clean up ruff config a bit

- include/bh_python/transform.hpp
See https://github.com/pybind/pybind11/pull/5580, fixed with the help of @rwgk, close #993.
> fix: use caster to support potential PyCapsule change in pybind11 3

- .github/workflows/tests.yml
- .github/workflows/wheels.yml
- pyproject.toml
> ci: add Windows ARM

- .github/CONTRIBUTING.md
- .github/workflows/tests.yml
- CMakePresets.json
- pyproject.toml
> chore: update tidy recipe and presets

- .github/CONTRIBUTING.md
- noxfile.py
> chore: bump boost version

- .github/workflows/wheels.yml
- README.md
See https://github.com/scientific-python/upload-nightly-action/issues/135.
> ci: anaconda nightlies

- .github/workflows/wheels.yml
- .pre-commit-config.yaml
- pyproject.toml
Pulled out from #1016 to test most recent RC.
> ci: add iOS wheels

- src/boost_histogram/serialization/__init__.py
- tests/test_serialization_uhi.py
> fix: move uhi schema to outer level

- .github/workflows/tests.yml
- .github/workflows/wheels.yml
- .pre-commit-config.yaml
- docs/changelog.md
- pyproject.toml
> docs: prepare for 1.6

- src/boost_histogram/serialization/__init__.py
- tests/test_serialization_uhi.py
Bringing this inline with hist/uhi implementations.
> feat: allow library to be specified in writer_info removal

- .github/workflows/wheels.yml
- pyproject.toml
> chore: this should work on iOS now in cibuildwheel
